### ISSUE TITLE
Spanish translation findings

### ISSUE THREAD

**Issue by fernandomartinez** [HugoGiraudel/sass-guidelines#106]
Here's one paragraph, please confirm if this is ok and useful, so I can continue checking the guide. Also please feel free to ignore anything you consider irrelevant.

On the first paragraph after the contribute title:
"Esta guía de Sass es un proyecto libre que mantengo en mi tiempo libre. Sobra decir que que es una cantidad enorme de trabajo para mantenerlo todo actualizado, documentado y relevante. Obviamente, apreciaré muchísimo saber que te ha gustado esta guía de estilo."

This could be:
"Sass Guidelines es un proyecto abierto que mantengo en mi tiempo libre. Sobra decir que lleva una cantidad enorme de trabajo mantenerlo vigente, documentado y relevante. Obviamente, apreciaré muchísimo saber que te ha gustado esta guía de estilo."

**Comment by HugoGiraudel** [comment]
Please, keep your comments about the Spanish translation on the Spanish translation issue. I'll port this one over.
