### ISSUE TITLE
Further explanation of 'layout/' compared 'pages/'

### ISSUE THREAD

**Issue by lchabela** [HugoGiraudel/sass-guidelines#112]
Was wondering if some one could help me understand the difference between layout and page. I have found reading the doc very enlightening and has helped a ton in organizing my client side styles. The only hic up i have found with me organizing with the '7-1' approach is that I am having a issue distinguishing what file should contain my adjustment styles for a module. 

Example scenario:
I have a list-group module that is place in a column in my application that is basically laid out in three columns. When the list-group is in these columns I would like to remove some styles on the module. Would it makes most sense to have a app column layout sass file or would it be best to treat the whole entire app as a page and make these adjustments in a page sass file?

I hope this is described clear enough for some help form this wonderful community, thank you in advance.

**Comment by HugoGiraudel** [comment]
`pages/` is reserved for very specific pages like the home page, the contact page and so on. The less styles in there, the better. Styles should be as modular as possible and not restricted to specific pages.

`layouts/` contains styles that build the layout and appear in all pages, for instance the grid system, the header, the footer, and so on.

`components/` should be the biggest part of your site. I think, in your case, your list-group should be a component (perhaps with a modifier if it behaves like this or that).

Hope it helps.

**Comment by lchabela** [comment]
Thank you that does help
