### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#114]
I think it might be interesting to version the guidelines, as follow:

* do not bump for language patches;
* bump patch for minor content changes (`x.y.+`);
* bump minor version for extra sections (`x.+.y`);
* bump major when (if) major revamp.

This way, it would be easy to figure out if a translation is up-to-date or not.

**Comment by PavelDemyanenko** [comment]
:+1:
