### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#137]
Ping @kimdhoe.

If you have any specific question regarding your translation, feel free to get in touch here. You will find all guidelines about translating this project in the meta issue: #96.

Cheers! :)

**Comment by kimdhoe** [comment]
Great! Thanks for the guidelines. For both of them :)

**Comment by kimdhoe** [comment]
Hey Hugo! Almost finished Korean translation. I have one question. Wondering if it would be OK to apply some exceptions to the guidelines.

I transliterated these *untranslated words* into Korean letters as it sounds. I think it would be more proper for Korean readers.

- front end / back end (noun)
- front-end / back-end (adjective)
- media query / media queries
- placeholder

Also, I translated *Responsive Web Design* to *반응형 웹 디자인*, which is a direct translation and widely used term in Korea.

**Comment by HugoGiraudel** [comment]
Hey Kim! 

No problem with those exceptions. I understand it really is specific to the language, so I trust your judgement on this.

Feel free to open a PR when you're done. I'll review (what I can review of course) and merge it. Also, be sure to add a `ko` (is that right?) key to both files in `_data` folder: https://github.com/HugoGiraudel/sass-guidelines/tree/gh-pages/_data. :)

**Comment by kimdhoe** [comment]
Oh and, in *Warnings and Errors* section,

> "Basically any mixin or function expecting a specific type **or** argument could throw an error if something went wrong, or display a warning when doing an assumption."

It is meant to be **of**, is it not?

I will open a PR soon!

**Comment by HugoGiraudel** [comment]
Yeah, could be.

**Comment by HugoGiraudel** [comment]
Relevant PR: #143. Closing.

**Comment by HugoGiraudel** [comment]
Please, could you submit a PR to update this line: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L120?

Adding something like ", translated by ..." in Korean, with Markdown links would be nice. Kind of what has been done for the Polish translation: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L100.

**Comment by HugoGiraudel** [comment]
Ping @kimdhoe. 

Do you feel like you could translate version 1.1.0? There are not many additions but that would be nice for your translation to remain up-to-date. You can see the changes here: https://github.com/HugoGiraudel/sass-guidelines/pull/125.

Tell me what you think. :)

**Comment by kimdhoe** [comment]
It's already been a season since 1.1.0?!  I'll speed up a little.

**Comment by HugoGiraudel** [comment]
No problem. :)
