### ISSUE TITLE
Put SCSS Lint config into a partial

### ISSUE THREAD

**Issue by Anahkiasen** [HugoGiraudel/sass-guidelines#147]
Currently the SCSS-Lint config is repeated in each language and will likely get slowly out of date in most of them as the main one gets updated. Would probably be better if it was abstracted into a partial or something that is then included in the languages

**Comment by HugoGiraudel** [comment]
Now that's brilliant.

**Comment by Anahkiasen** [comment]
Do note that that is also true for most of the code examples that don't contain any comments needing a translation, like the long list of `@import` here per example http://sass-guidelin.es/#main-file

**Comment by HugoGiraudel** [comment]
True, however this is unlikely to move a lot, unlike the SCSS-lint conf.

**Comment by Anahkiasen** [comment]
Yeah I'm actually waiting for SCSS-Lint to tag a 0.34 to update Sass Guideline's ruleset, lots of good things in the new versions

**Comment by HugoGiraudel** [comment]
There: https://github.com/HugoGiraudel/sass-guidelines/pull/148.
