### ISSUE TITLE
respond-to mixin could be more robust

### ISSUE THREAD

**Issue by xzyfer** [HugoGiraudel/sass-guidelines#150]
Sparked by an issue originally reported by @kevinsimper on https://github.com/sass/libsass/issues/891.

I am aware it comes with the below warning, but this doesn't stop people copy-pasting it.

> Obviously, this is a fairly simplistic breakpoint manager that will not do the trick when dealing with custom and/or multiple-checks breakpoints.

As it stands this mixin could support more complex query lists if the breakpoint value where unquoted (if it's a string of cause). e.g. http://sassmeister.com/gist/9e8e20ffe4ca184321b7

**Comment by HugoGiraudel** [comment]
I like that. I might update it. :)

**Comment by xzyfer** [comment]
Great to hear. I've closed the related Libsass issue.

**Comment by HugoGiraudel** [comment]
Done for 1.0.1: https://github.com/HugoGiraudel/sass-guidelines/commit/87eb7c2eea03d70c964c416d5356291f89224451.
