### ISSUE TITLE
Proposal for visual improvement

### ISSUE THREAD

**Issue by PavelDemyanenko** [HugoGiraudel/sass-guidelines#154]
Hi Hugo!

There are some visual bugs on first loading (e.g half styled sidebar moving left). You can check it [here](https://www.dropbox.com/s/7yxlvkrt6lw0kuf/Screencast%202015-02-27.mp4?dl=0), I've made a short screencast. Maybe some workaround should be created (e.g preloading overlay) or maybe kind of refactoring.

What do you think about it?

**Comment by HugoGiraudel** [comment]
Actually this is kind of intended. The thing is I use asynchronous CSS loading, causing little FOUC, but dramatically improving initial load performance. I might try to improve this specific thing though.

**Comment by PavelDemyanenko** [comment]
Thanks for the clarification! Closing this issue.
