### ISSUE TITLE
Just a little unclear sentence in the english intro

### ISSUE THREAD

**Issue by Nicolas-Pare** [HugoGiraudel/sass-guidelines#159]
Hi there,

You tell in the intro you will be doing the guide in SCSS cause it's more like CSS. But in fact we have the choice in the option. It would be great I think to mention that at the beginning.

Tanks for the great guideline probably the best and more complete I never read.
Nicolas Paré

**Comment by HugoGiraudel** [comment]
I need to updated that. Thanks.

**Comment by HugoGiraudel** [comment]
Actually it is already done on `develop` branch and will be live when 1.0.1 get released (soon). :)

**Comment by Nicolas-Pare** [comment]
Nice! Keep the good job;)

**Comment by HugoGiraudel** [comment]
Released, by the way. :)
