### ISSUE TITLE
Portuguese Brazilian translation 

### ISSUE THREAD

**Issue by edmolima** [HugoGiraudel/sass-guidelines#162]
Hello @HugoGiraudel ,

I can help in translation for Brazilian Portuguese :)

I have started something, then could go on!

Let me know if I can get involved!

**Comment by HugoGiraudel** [comment]
Terrific! :)

**Comment by jhonnymoreira** [comment]
@devedmo I would like to help too. Can I?

**Comment by devedmo** [comment]
@jhonnymoreira yes we go together!

I've done a fork and started something here: [sass-guidelines](https://github.com/devedmo/sass-guidelines) 
started something, we can divide like this:

architecture to loops - can i translate were already started.

mixins to variables - you could do.


Can it be like this? or have other suggestions?

**Comment by jhonnymoreira** [comment]
@devedmo Sweet! How about we do something like this and then committing the things made?
https://github.com/HugoGiraudel/sass-guidelines/issues/89#issuecomment-70537827

**Comment by jhonnymoreira** [comment]
@devedmo This is fine. If you want to change things a little bit, there is this comment with a good pattern to follow: https://github.com/HugoGiraudel/sass-guidelines/issues/89#issuecomment-70537827

See if it's nice for you and then ping me. While we don't have a formal way to continue, I'm translating the Author and Comments sections. You can find the changes in here https://github.com/jhonnymoreira/sass-guidelines.

**Comment by devedmo** [comment]
@jhonnymoreira you talk of division that friends use? I had even thought about it, I think a great idea. do you agree? 

We can follow the same pattern, just think it would be better to centralize on a branch. can be in your fork? 

why in the future, we can make a single merge with Hugo.

**Comment by jhonnymoreira** [comment]
@devedmo Of course it can be. [=

By the way, if you have any way to contact you, such as facebook, twitter (direct messages) or even Skype, let me know. It would be great to keep contact with you about the project and other stuff.

**Comment by jhonnymoreira** [comment]
@devedmo I updated the source of the fork: https://github.com/jhonnymoreira/sass-guidelines

I'll create a branch called "pt-br" and we work on that, ok?

**Comment by HugoGiraudel** [comment]
I like when things roll out, nice to see you guys getting along with each other. Regarding the final merge, ideally just submit a PR and tell me when you want me to review it. :)

**Comment by jhonnymoreira** [comment]
Thank you, @HugoGiraudel! [=

I'll be doing a late night translation. I'm fixing some things in _architecture.md, but my guess is that today I release two to three translated sections.

@HugoGiraudel, I see that some changes happened and the version is now on 1.1.0. I'll try to translate the changes made as soon as possible.

**Comment by jhonnymoreira** [comment]
@devedmo I saw that I was doing some shit while commiting, because my messages were in portuguese.

When you commit, use something like this:
`translated: _author.md, _contributing.md`
`translating: _comments.md`
`fixing: _author.md`
`translated: _author.md, _contributing.md; fixing: _author.md`

On the folder `pt-br/`, there is a file called `README.md` with some GitHub Markdown to keep track of translated things. Finished the translation? Check what you translated in the file.

**Comment by devedmo** [comment]
@jhonnymoreira no problems! I did a pull now, I will send my modifications and continue where I left off.

**Comment by douglasdeodato** [comment]
@edmolima  @jhonnymoreira @HugoGiraudel  what is the story about the pt-br translate? still need a help?

**Comment by jhonnymoreira** [comment]
@douglasdeodato I've been through some stuff that kept me away from the translation and programming, but I got back this month. Do you want to do a pair translation with me? I'm available full time right now.

**Comment by douglasdeodato** [comment]
@jhonnymoreira  Hi Jhonny , off course we can start do this together why not 👍

**Comment by HugoGiraudel** [comment]
Moving to #361.
