### ISSUE TITLE
Choose more internationalized font

### ISSUE THREAD

**Issue by Grawl** [HugoGiraudel/sass-guidelines#167]
As you can see, Cyrillic letters looking not so thin as Latin. Especially in headings.
I offer to switch to one of Google Fonts with Cyrillic support (Open Sans for example).
Additionally I offer to choose good font for Chinese. I think we can ask for opinion of Chinese translation author.

**Comment by HugoGiraudel** [comment]
Currently running Droid Sans. Do you think Open Sans will be any better?

**Comment by Grawl** [comment]
Hmm. Droid Sans must support Cyrillic. It's Google Fonts or local?

**Comment by HugoGiraudel** [comment]
Data encoded font file downloaded from Google Font.

**Comment by Grawl** [comment]
Oh I see. Now [Droid Sans on Google Fonts](http://www.google.com/fonts#UsePlace:use/Collection:Droid+Sans) supports only Latin script.
I have two solutions:

- I can send you my own Droid Sans with cyrillic script
- We can change font to one of Google's [Cyrillic-supported](http://www.google.com/fonts#ChoosePlace:select/Script:cyrillic) 25  sans-serif fonts (I like Open Sans, Roboto or PT Sans)

**Comment by HugoGiraudel** [comment]
Okay, we will switch on a Cyrillic-supported font.

**Comment by HugoGiraudel** [comment]
See #171.
