### ISSUE TITLE
Externalize code blocks into their own partials

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#181]

**Comment by HugoGiraudel** [comment]
I was thinking of moving all code snippets into separate files. This would not only greatly reduce the size of actual content files (especially `_syntax.md` which is extremely long), but also would make maintaining the project way easier.

The downside is that code blocks would now be shared between all translations, making them impossible to translate. Basically, we would leave inline comments in English. Do you feel like this is a deal breaker?

Regarding the technical implementation, it would be quite easy. In the `_includes/` folder would be a `snippets/` folder containing a sub-folder per chapter containing code snippets (`architecture/`, `comments/`...). In each sub-folder, files are numbered (`01.html`, `02.html`...) and so on. Finally, in content files, instead of having the HTML snippet for the code, we would only have something like:

```
{% include snippets/architecture/01.html %}
```

What do you think?

Ping all: @varemenos, @kmargaritis, @pierrechoffe, @ttomdewit, @bartveneman, @klapec, @matchabros, @kaibrueckers, @altembo, @magalhini, @couto, @saravieira, @eduardoboucas, @soniar4i, @davidkpiano, @srescio, @pavelantolik, @grawl, @PavelDemyanenko, @airen, @pinggod, @kimdhoe.

**Comment by pierrechoffe** [comment]
Hi Hugo,

While this would obviously make our lives easier, I think this wouldn’t help our readers. Chances are they choose their native language version because they have problems reading the English version, so they would probably miss something in the end. User experience is more important than translators experience, so I for one would not mind keeping the file organisation as is.

Cheers,
Pierre

**Comment by HugoGiraudel** [comment]
Keep in mind we are only talking about keeping the few comments there are in code blocks in English.

**Comment by pierrechoffe** [comment]
Sure man, but this is an important part of it ! I recently sent the sass-guidelines link to someone as a comment to his post in Google+, the questions I got from him in return related to the code. Sometimes the comments in the code blocks bring substantial infos (e.g. in the scope section)
Now, this is only my point of view and this is your article, so the decision is yours :))

@+, p

**Comment by HugoGiraudel** [comment]
Thank you for your opinion @pierrechoffe. I'd like to hear more before taking a decision. :)

**Comment by Grawl** [comment]
@HugoGiraudel I see why you want to do that. Cleaning of Markdown files and moving all code snippets to one place where translators cannot corrupt important parts is good idea, …

But I am completely agree with @pierrechoffe about importance of code comments translating.

Can we surround all code snippets with three tildes with language specification in style of GitHub Powered Markdown? Like this:

    ```scss
    // code
    ```

This will help us read it in our editors.

*Also, I think we are have to create contributing guideline where will be rules about code, about names, all this important things.*

**Comment by HugoGiraudel** [comment]
> Also, I think we are have to create contributing guideline where will be rules about code, about names, all this important things.

I'll tackle this.

If you guys think it's important to translate comments within code blocks (which is not done in all translations by the way), one way to fix the problem would be to externalize this content outside of the code blocks to leave nothing but code within them.

**Comment by Grawl** [comment]
You mean something like this?:

> Since Sass indented-syntax forces those coding standards.
> There is no wrong way of proceeding.
> 
>```sass
> .foo
>  display: block
>  overflow: hidden
>  padding: 0 1em
>```

Instead of existing approach like this?:

>```sass
>// Since Sass indented-syntax forces those coding standards
>// There is no wrong way of proceeding
> .foo
>  display: block
>  overflow: hidden
>  padding: 0 1em
>```

This will be easy. But what about the complex parts?

Like SassDoc:

>```sass
>/**
> * 1. Magic number. This value is the lowest I could find to align the top of
> * `.foo` with its parent. Ideally, we should fix it properly.
> */
>.foo
>  top: 0.327em /* 1 */
>```

Or comments in the middle of code:

>```sass
>/// Slightly lighten a color
>/// @access public
>/// @param {Color} $color - color to tint
>/// @param {Number} $percentage - percentage of `$color` in returned color
>/// @return {Color}
>@function tint($color, $percentage)
>  @return mix($color, white, $percentage)
>```

We have to translate only non-technical parts of a comments, like “$percentage - percentage of `$color` in returned color” to “$percentage - процент от `$color` в возвращаемом цвете” (ru).

**Comment by HugoGiraudel** [comment]
Comments in the SassDoc section are only there to present the idea behind SassDoc; we don't actually care much about the content so I am not too worried about it. 

I think, comments in the middle of code such as the one you just presented are the most complicated case to handle. Now, if it's one case in the whole guidelines, I am willing to trade this for better maintenance. Let's keep in mind we currently have 7 versions, and are willing to include 6 to 8 more.

**Comment by Grawl** [comment]
I think we can handle your idea by translating code snippets in separate files with postfixes in their names, like `snippet-10-en.md` and `snippet-10-ru.md` or something similar. If no need to translate just don't add a postfix. This will be a good approach.

**Comment by HugoGiraudel** [comment]
I like it.

Le dim 19 avr. 2015 17:55, Даниил Пронин <notifications@github.com> a
écrit :

**Comment by HugoGiraudel** [comment]
Okay, here we have a version allowing code snippets to be translated: https://github.com/HugoGiraudel/sass-guidelines/pull/184/files.

Here is how it works (with `/fr` as an example):

1. `/fr/index.html` includes `/_includes/chapters.html`, describing the order of chapters;
2. `/_includes/chapters.html` includes all chapters from the French version (e.g. `/fr/_comments.md`);
3. chapters with code snippets includes them (e.g. `/_includes/snippets/comments/01/index.html`)
  * if the relevant code snippet does not need a translation, then the index file only contains the snippet HTML;
  * if the relevant code snippet contains some content that should be translated (such as comments), it includes the current language's version (e.g. `/_includes/snippets/comments/01/fr.html`).

Remaining question: should code snippets be numbered or named (currently numbered)? I think named would make more sense.

**Comment by Grawl** [comment]
Like it; now we have a good architecture.

> Remaining question: should code snippets be numbered or named (currently numbered)? I think named would make more sense.

I think names will be better than numbers. And we can mix em. For example, we can use chapter name for one part and number for second. For example, in [Color Formats](http://sass-guidelin.es/#color-formats) we have two snippets, so name it like `color-formats-1.html` and `color-formats-2.html`.

**Comment by HugoGiraudel** [comment]
Nope. If I am to remove numbers, I remove numbers altogether to keep meaningful names only. Problem with numbers is they are useful until you the order gets changed, which is very likely. To prevent this issue, I think I'll try to find a name for all code snippets.

**Comment by Grawl** [comment]
Okay, you know – you do :)

**Comment by HugoGiraudel** [comment]
Will probably get merged at some point during the week.
