### ISSUE TITLE
Rename NodeJS to Node.js

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#196]
This is *seriously* not a real issue, but rather a little correction I would like to approach. *Don't take it too seriously ;)*

The official name is **Node.js**, not NodeJS.
Reference: 
- http://en.wikipedia.org/wiki/Node.js
- https://nodejs.org/about/

Best,
Moritz

**Comment by HugoGiraudel** [comment]
Good point. I'll tackle this.

**Comment by morkro** [comment]
That was pretty fast! I'll also fix it right away in the german translation.
