### ISSUE TITLE
Cover @keyframes and general animation usage

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#201]
I think this would be useful. Some thoughts from my side:

- Do you place them in the file where it's used? So that everything is treated as a component and at one place.
- What about `@keyframes ` which are used across different elements? Would a  `_keyframes.scss` file make sense? If yes, which folder?
- Mixins?
- Any syntax conventions? For instance: never use 
````
from {
  ...
} 
to {
  ...
}
````
or maybe even
````
0% {
  ...
} 
100% {
  ...
}
````

What do you think?

**Comment by HugoGiraudel** [comment]
Regarding where to put animations, I feel like I could add a note in the Architecture section. Regarding the syntax conventions, I won't tackle them as they are strictly CSS related and out of the scope of Sass Guidelines. 

I might add something about bubbling as well.

**Comment by HugoGiraudel** [comment]
Added in https://github.com/HugoGiraudel/sass-guidelines/commit/efb8863b6f4427d3df8d08b01c14e5d7e08b3226.
