### ISSUE TITLE
Consistent use of "//" in code samples.

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#204]
Well, um, yeah. I'm feeling really picky now. Sorry for that. And, again, it's not a real issue anyway.

You mix `//` and `///` in your code samples.  For instance:
> // Add current module to the list of imported modules.
> // `!global` flag is required so it actually updates the global variable.

and 

> /// Vertical rhythm baseline used all over the code base.
> /// @type Length

_Just ignore me._

Cheers,
Moritz

**Comment by jhonnymoreira** [comment]
When you use something like `///` is because of [SassDoc](http://sassdoc.com/) documentation style. When you use `//` are just simple comments to explain what's happening on a line of code or  a block of code. [=

**Comment by HugoGiraudel** [comment]
This.

**Comment by morkro** [comment]
Ah, that wasn't clear for me. Understood ;)
