### ISSUE TITLE
Add font family names to code element, especially for ko and zh.

### ISSUE THREAD

**Issue by kimdhoe** [HugoGiraudel/sass-guidelines#208]
It seems that some browsers show an unexpected behavior when `lang` attribute is set to _ko_, resolving generic family _monospace_ to a font that is not monospace.

![monospace_ko](https://cloud.githubusercontent.com/assets/10362796/7713929/ebe0a8f4-feb5-11e4-804d-b62dad5ac2ed.png)

I've tried Safari, Firefox, and Chrome on OS X and only Chrome managed to choose fixed-width font. The result was the same in `zh` version on Safari.

Can we explicitly specify font family names for `code` element other than generic family?

**Comment by jhonnymoreira** [comment]
Using the **Firefox Developer Edition 38.0a2 (2015-03-27)** and setting `font-family: "Monaco";` in `.highlight code`, the code was being displayed properly.

**Comment by HugoGiraudel** [comment]
That's odd. I'll see what I can do. Thanks for reporting.

**Comment by kimdhoe** [comment]
I guess these browsers simply choose proportional width Hangul font, because there is no fixed width Hangul font installed on my machine. Fixed width Hangul font is rare, if any at all. Resolving the generic family, they seem to put _which language the content is written_ before _which type of family is specified_.

**Comment by kimdhoe** [comment]
Hi @HugoGiraudel: I just noticed "_Source Code Pro_" is already being fetched using `@font-face`, but no text is using it. It's being wasted on `<pre>`, which is a parent of `<code>`, which has its own `font-family` property with the value of `monospace`.

**Comment by HugoGiraudel** [comment]
It is now fixed. Is the issue still relevant?

**Comment by kimdhoe** [comment]
No, it's perfect!

**Comment by kimdhoe** [comment]
@HugoGiraudel Oh wait, `code` that is not decendent of `pre` is still the same.

**Comment by HugoGiraudel** [comment]
Damn, I suck.

**Comment by HugoGiraudel** [comment]
Should be fine now?

**Comment by kimdhoe** [comment]
That was fast. It's really perfect now! Beautiful.

**Comment by HugoGiraudel** [comment]
Thank you very much for being involved in Sass Guidelines. I am proud to have such great contributors as you. :)

**Comment by kimdhoe** [comment]
You're welcome. Actually I am proud to be part of this.
