### ISSUE TITLE
Unitless zero doesn't work for durations

### ISSUE THREAD

**Issue by dlwalsh** [HugoGiraudel/sass-guidelines#217]
From the guidelines:

> ## Numbers
>
> In Sass, number is a data type including everything from unitless numbers to lengths, durations, frequencies, angles and so on. This allows calculations to be run on such measures.
>
> [..]
>
> ### UNITS
>
> When dealing with lengths, a 0 value should never ever have a unit.

I realise that this guideline pertains specifically to lengths. But once it becomes a habit, it's natural to extend this practice to other types of numbers. In particular durations, which don't allow for the unitless zero. That is, a plain 0 is not a valid value for any of the following properties:

* animation-delay
* animation-duration
* transition-delay
* transition-duration

I think the guidelines should make the limitations of this practice clear. I know it's brought me unstuck in the past. It would be good to prevent others falling into the same trap.

**Comment by HugoGiraudel** [comment]
Seems fair. :)

**Comment by HugoGiraudel** [comment]
Added in https://github.com/HugoGiraudel/sass-guidelines/commit/12d33dd69145b12593c15b245451f6bcbc288089.
