### ISSUE TITLE
Rethink “Further readings” sections

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#226]
I was thinking of having less further reading sections. Maybe only one at the end of a chapter (Sass, Syntax, Mixins, Loops, Errors...). Currently, we have them in almost all sections and sub-sections and I don't feel so well about it; it might be distracting when reading the guidelines from top to bottom, it is not great for screen-readers...

Other idea: stuff them as much as possible in the text, inside of after it.

Do you folks have an opinion?

Ping @pierrechoffe, @klapec, @matchabros, @morkro, @soniar4i, @davidkpiano, @grawl, @PavelDemyanenko, @airen, @pinggod, @kimdhoe, @AndersSchmidtHansen, @srescio, @HoBi, @ttomdewit, @bartveneman, @varemenos, @magalhini, @couto, @saravieira, @eduardoboucas.

**Comment by bartveneman** [comment]
I don't really see them as distracting, although I get your point about them being a little distracting. Perhaps it would help to add some slightly muted sidebar or block where they are listed, so the reader doesn't get interrupted from the document flow. Their location in the document is ok, as @davidkpiano said: the text provides excellent context for those links. Grouping them per chapter would make it more difficult to see what information a link will provide.

**Comment by AndersSchmidtHansen** [comment]
Hmm, like @davidkpiano I personally got a lot out of having a separate section dedicated to inspiration. It fits my mental model better. Like, I read through a section of guidelines and then I can go "aight, got that, now what else is there".

If the further reading would be moved into the paragraphs themselves as inline links, I imagine that I would read parts of the guidelines only to get interested in clicking on a link and forget all about finishing that particular section of guidelines. But that would be judging from my own behavior.

What about making it more clear where one section starts and another begins? Something as subtle as a horizontal line and some extra margin. I think that could make the further reading sections more tied-in to each section, possible making them less distracting? Just an idea.

**Comment by HugoGiraudel** [comment]
> What about making it more clear where one section starts and another begins?  Something as subtle as a horizontal line and some extra margin. I think that could make the further reading sections more tied-in to each section, possible making them less distracting? Just an idea.

Yes. I always thought the guidelines where not enough *chapter-y*. I'll work on this.

> Perhaps it would help to add some slightly muted sidebar or block where they are listed, so the reader doesn't get interrupted from the document flow. 

I like it. I feel like on large screens it would be interesting to do so. Do you have any design idea maybe?

**Comment by morkro** [comment]
A sidebar sounds like a great idea. A table of contents in the sidebar would also help a lot for me.
I always find myself scrolling all to the top, just to _jump_ to a new section.

The further readings are, as for all so far, absolutely fine. Fits my flow and doesn't interrupt at all.

**Comment by HugoGiraudel** [comment]
Let's create a new issue to deal with the ToC.

**Comment by bartveneman** [comment]
> A table of contents in the sidebar would also help a lot for me.

Perhaps something like [sphinx theme](https://github.com/snide/sphinx_rtd_theme) does, as seen on [Slim documentation](http://docs.slimframework.com/).

> I like it. I feel like on large screens it would be interesting to do so. Do you have any design idea maybe?

I have no clear idea about it, at least not design-wise. It could be nice to make it a sticky, visually muted element, that gets highlighted once you hover it (don't know about touch devices yet).

**Comment by bartveneman** [comment]
Just trying to think out of the box: Maybe some footnote-like system might help too, for really specific cases.

**Comment by HoBi** [comment]
I would personally let further reading for each chapter as is now. Maybe only hide that under some slider connected to a button?

**Comment by HugoGiraudel** [comment]
I am fine with keeping further readings as they are now, but I want to move them in a sidebar or something. I don't like the amount of space they take in the content. I think this is unnecessary as many people don't care about reading suggestions.

**Comment by bartveneman** [comment]
What I actually meant style-wise was mentioned by @morkro in #227: HtmlRocks gets it right in ways of contrast and readability. I'd only pick the style for further reading and not TOC.

**Comment by pierrechoffe** [comment]
Hi Hugo,
As a reader I'm always happy to have a lot of reading material so I
wouldn't bother. We can assume that your readers on Sass-Guidelines are
willing to learn, therefore it would be nice for them to have additional
food for thought. Why don't you feel well about these? Do you think it's
kind of messy or something?
Well, that's my opinion, but what do you guys think?
Cheers,
Pierre

2015-07-21 15:08 GMT+02:00 Hugo Giraudel <notifications@github.com>:

**Comment by varemenos** [comment]
I personally enjoy the further reading sections, you can find some really great gems in there. I understand though that some readers might find them tiring or distracting.

Having one at the end of chapter sounds like a great idea.

**Comment by AndersSchmidtHansen** [comment]
There's just something bugging me about the whole "some readers" / "many people" thing. Is this an assumption or is this based on data? :) As far as I can read from these comments, then what 6-7 already state that the further reading section is all fine and good as it is.

EDIT: This sounded a bit more provocative than intended, it was truly more a random thought.

**Comment by HoBi** [comment]
What about make another checkbox in menu like current for Sass vs SCSS syntax? Can Jekyll remember user's IP?

**Comment by morkro** [comment]
Jekyll is simply a static site generator :) There is no backend running. You can get the users IP via JavaScript and an external API though, but that's more hacky and not pretty accurate.

**Comment by HoBi** [comment]
@morkro I know. I put the wrong question... :)


We can use cookies (client side method) and hide the "further reading" for users who chcecked "I do not want to see further reading"? Also it would be nice to have some start animation with settings including Sass/SCSS and more, but that may does rather poor experience, I do not know. :smirk_cat:

**Comment by HugoGiraudel** [comment]
Let's keep it like this, it seems to be alright for most people.
