### ISSUE TITLE
Keep the ToC along the page

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#227]
Any idea?

**Comment by HugoGiraudel** [comment]
From @bartveneman in #226.

> A table of contents in the sidebar would also help a lot for me.

Perhaps something like [sphinx theme](https://github.com/snide/sphinx_rtd_theme) does, as seen on [Slim documentation](http://docs.slimframework.com/).

**Comment by HoBi** [comment]
@HugoGiraudel I really like interactive sidebars such as http://getbootstrap.com/components/

**Comment by morkro** [comment]
I really like the HTML5Rocks sidebar which slightly fades out after some time: http://www.html5rocks.com/en/tutorials/es7/observe/

**Comment by AndersSchmidtHansen** [comment]
This could be fixed pretty easily with the Bootstrap Affix http://getbootstrap.com/javascript/#affix. I've used it a couple of times, pretty straightforward, nothing to fancy, but gets the job done.

**Comment by morkro** [comment]
Well it's pretty simple right? Just check the position of the element on a scroll event. To be honest, I don't think a library is necessary for this.

**Comment by AndersSchmidtHansen** [comment]
True @morkro, no need to add extra fluff to the site just for the sake of it. I agree.

**Comment by morkro** [comment]
@HugoGiraudel: I have the same exact functionality for my upcoming website relaunch. We could use my simple snippet for that. If that would be okay for you.

**Comment by HugoGiraudel** [comment]
It would.

**Comment by HugoGiraudel** [comment]
There is a pull-request pending for this: #236. If someone wants to try it locally and give me an opinion, that would be super rad. :)

To do: affix. Not sure how to tackle this. Care to dive in @morkro?

**Comment by morkro** [comment]
Sorry, for the delay here.
Sure, would like to do that! Will spend some time on that tomorrow and get back to you :)

**Comment by HugoGiraudel** [comment]
Done. :)

**Comment by HoBi** [comment]
Very nice. :+1:
