### ISSUE TITLE
Add extra further reads

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#237]
So here is the thing. I plan on removing a lot of further reads in version 1.2.0. First run can be seen in this commit: https://github.com/HugoGiraudel/sass-guidelines/commit/047fc30c0157659ce47ffacd1d5fd9522d47cbe1.

My point is to remove all links that are already present in the text as it makes no sense to have them twice. I also got rid of all links to homepage of services and products such as Sass, LESS, Stylus, PostCSS, cssnext, SassDoc, SCSS-lint and so on. They are not further reads per se.

Now, I would like to add some extra relevant and meaningful further reads. If you folks have any idea, be sure to tell. I'll go through everything and see how I can put them in the guidelines (if I can).

**Comment by HugoGiraudel** [comment]
So here is the thing. I plan on removing a lot of further reads in version 1.2.0. First run can be seen in this commit: https://github.com/HugoGiraudel/sass-guidelines/commit/047fc30c0157659ce47ffacd1d5fd9522d47cbe1.

My point is to remove all links that are already present in the text as it makes no sense to have them twice. I also got rid of all links to homepage of services and products such as Sass, LESS, Stylus, PostCSS, cssnext, SassDoc, SCSS-lint and so on. They are not further reads per se.

Now, I would like to add some extra relevant and meaningful further reads. If you folks have any idea, be sure to tell. I'll go through everything and see how I can put them in the guidelines (if I can).

**Comment by HugoGiraudel** [comment]
Ping Ping @pierrechoffe, @klapec, @matchabros, @morkro, @soniar4i, @davidkpiano, @grawl, @PavelDemyanenko, @airen, @pinggod, @kimdhoe, @AndersSchmidtHansen, @srescio, @HoBi, @ttomdewit, @bartveneman, @varemenos, @magalhini, @couto, @saravieira, @eduardoboucas, @wood1y, @jhonnymoreira, @mattcav.

**Comment by dkebler** [comment]
http://thecodingdesigner.com/journal/balancing-ideal-sass-and-ideal-css

**Comment by HugoGiraudel** [comment]
Thank you @dkebler.

I will have a look on my side if I can improve the further reading sections. 1.2.0 is likely to be released early September.

**Comment by HugoGiraudel** [comment]
Done in https://github.com/HugoGiraudel/sass-guidelines/commit/7da7f933a70c11899a189e472e9b80adf76e0204.
