### ISSUE TITLE
Problem between sidebar and footer

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#242]
https://twitter.com/anatomic/status/624530354167283712

**Comment by HoBi** [comment]
@HugoGiraudel Also, sometimes, on fast scroll to top it overlaps a part of header until it fixs.

**Comment by HoBi** [comment]
More than year ago I made a [sticky menu](http://www.itnetwork.cz/jquery-tutorial-sticky-menu-a-sidebar). It is easy and you have to only switch between 2 CSS classes.


Something like this works fine, just add a condition for footer break. :)
_(+ change the .css() functions to toggleClass)_
```
$(function(){
	fixAside();
});

function fixAside()
{
	var sticky = $('.sticky').offset().top;
	var menu = $('nav');

	$(window).scroll(function(){
		var scroll_top = $(window).scrollTop() + menu.height();

		if (sticky < scroll_top){
	  		$('.sticky').css({ position: 'fixed', top: menu.height() });
		}
		else {
	  		$('.sticky').css('position','static');
		}
	});
}
```

The condition may be something like 

```
else if (sticky+sticky.outerWidth() > scroll_footer) {
    $('.sticky').css('position','static'); // + change this
}
```

**Comment by HoBi** [comment]
![asdasda](https://cloud.githubusercontent.com/assets/5287596/8888947/aabc01f6-32c3-11e5-899c-ca601660ad3a.gif)

**Comment by HugoGiraudel** [comment]
I don't use jQuery on Sass Guidelines. Regarding the header overlapping, it
happens because the sticky behaviour passes through a debounce function to
avoid killing scroll performance.

Le sam 25 juil. 2015 16:53, Honza Bittner <notifications@github.com> a
écrit :

**Comment by morkro** [comment]
Yes, as Hugo already pointed out, the delay happens due to the `debounce` function. 
Sass-Guidelines aims at achieving best performance, hence this was seen as needed in the first place.
I will try to address this behaviour as well, when debugging the actual issue here :)
