### ISSUE TITLE
7-1 Pattern @import order - Utils before Vendor?

### ISSUE THREAD

**Issue by mikemclin** [HugoGiraudel/sass-guidelines#256]
I noticed when viewing the load order for the [main.scss](http://sass-guidelin.es/#main-file) file, it lists `vendor` ahead of `utils`.

Taking **Bootstrap** as an example, wouldn't I want my `utils` to be loaded first (since that is where my `_variables.scss` lives)?

Otherwise, vendor settings like `$brand-primary: #0275d8 !default;` in Bootstrap will always be the default value, because no `$brand-primary` exists, since we loaded our `$brand-primary` after Bootstrap.

**Comment by HugoGiraudel** [comment]
If you load your own file containing `$brand-primary` after Bootstrap, then it will override the value from Bootstrap. I don't see the problem. :)

**Comment by mikemclin** [comment]
I change `$brand-primary` to **red** in my `_utilities.scss` file.

I load files in the following order...

* `vendor/bootstrap/_variables.scss`
* `vendor/bootstrap/_buttons.scss`
* `utils/_variables.scss`

My primary colored button is Bootstrap blue, not red.

However, if I load it in this order...

* `utils/_variables.scss`
* `vendor/bootstrap/_variables.scss`
* `vendor/bootstrap/_buttons.scss`

My primary colored button is red.

It seems that if we don't load our variables before the library variables, then it renders the `! default` declarations in the lib variables pointless.  Isn't that why they are there?  So we can define our custom variables and let the library fill in the undefined variables with defaults?

**Comment by HugoGiraudel** [comment]
Oh, true. That's right, I need to fix it. Thanks for the report. :)

**Comment by HugoGiraudel** [comment]
Done with https://github.com/HugoGiraudel/sass-guidelines/commit/4546afec569c7ea8fc77831a50c562db9e2389b8.
