### ISSUE TITLE
About double quotes

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#26]
Some developers pointed out that double quotes are a pain to type on qwerty keyboards. That may be a reason valid enough to switch to single quotes.

**Comment by tobysteward** [comment]
I'm a big fan of single quotes personally - for no reason in particular. [From the W3C](http://www.w3.org/TR/CSS21/syndata.html#uri):

> The format of a URI value is 'url(' followed by optional white space followed by an optional single quote (') or double quote (") character followed by the URI itself, followed by an optional single quote (') or double quote (") character followed by optional white space followed by ')'. The two quote characters must be the same.

So it really is potato potahto!

**Comment by HugoGiraudel** [comment]
Single quotes have been merged. :)
