### ISSUE TITLE
Use HSL | RGB instead of Hex

### ISSUE THREAD

**Issue by Swelly** [HugoGiraudel/sass-guidelines#262]
Small tweak regarding a variable named $sass-pink. It's declared using HEX when the previous section specifically asks for HSL | RGB notation.

http://sass-guidelin.es/#colors-and-variables

**Comment by HugoGiraudel** [comment]
Do you mind submitting a PR maybe?

**Comment by HugoGiraudel** [comment]
Done: https://github.com/HugoGiraudel/sass-guidelines/pull/278.
