### ISSUE TITLE
Add `_init.scss` for initialization

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-guidelines#267]
I suggest adding `_init.scss` that would be first in `utils` (or `abstracts`) and hold initialization of some variables taht are needed by frameworks like [Zen Grids](https://github.com/JohnAlbin/zen-grids) or [Susy](https://github.com/ericam/susy).

Some frameworks need variables before loading (just read somewhere, not sure which one) but it doesn't hurt and makes sense to separate **initialization** from **variables**.

**Comment by HugoGiraudel** [comment]
Frameworks should be self-reliant, which means they should come with default configuration and should not mandatorily require variables to be defined before their inclusion. While it might be sometimes needed (I do not deny that), it is not something that should be part of Sass Guidelines.
