### ISSUE TITLE
Load `utils` (abstracts) before vendor

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-guidelines#268]
I also think that `utils` (or `abstracts`) should be loaded **before** `vendor` things that actually may produce some output like `_normalize.scss`. In my opinion, loading order should be:

1. **abstracts** _(initialization - no code, probably should also include codeless frameworks like zen or susy)_
2. **vendor** _(reset and frameworks that produce some code)_
3. **base** _(element styling and common site-wide stuff)_
4. **layout** _(where all layout lives)_
5. **components** _(movable widgets)_
6. **page** _(page specifics)_
7. **theme** _(reskinning where needed)_

**Comment by HugoGiraudel** [comment]
Already the case.
