### ISSUE TITLE
Change normalize.css to John Albin _normalize.scss

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-guidelines#269]
The current version is actually just inlcuded `normalize.css`.

[@JohnAlbin](https://github.com/npmcomponent/JohnAlbin-normalize-scss) is truly **sass**, offer some control on final output and is based on currently included [@necolas normalize.css](https://github.com/necolas/normalize.css)

**Comment by HugoGiraudel** [comment]
This actually does not belong to the Sass Guidelines repository but to the boilerplate.

**Comment by macmladen** [comment]
Ah, by the end of the day I seem to loose concentration - I figured out that previous issue should be divided. This is now in **sass-boilerplate**.
