### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#273]
How about adding a `CHANGELOG` file for contributors/ translators?

It can be hard updating and maintaining a translation, especially if you have fallen behind several releases. The `CHANGELOG` could point to added/modified/deleted sections and give an overall sense of how much work an update could be. Good for personal estimations!

**Comment by HugoGiraudel** [comment]
Is this something you would be interested in tackling, Moritz? Feel free to decline, I won’t take it personally. :D

**Comment by morkro** [comment]
Will do it! :wrench:

**Comment by HugoGiraudel** [comment]
Done in #291.
