### ISSUE TITLE
Migrate to Jekyll 3

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#280]
Jekyll 3 has been released a few days ago and it would be nice if we could port Sass Guidelines over. I would like to see if this new version is likely to solve compile performance issues we had because of the massive number of nested partials includes.

**Comment by emilyzheng828** [comment]
It seems to be working on Jekyll 3.

**Comment by HugoGiraudel** [comment]
Oh. Interesting. Anything specific we should take care of maybe?

**Comment by HugoGiraudel** [comment]
Seems to work perfectly. :)

**Comment by emilyzheng828** [comment]
Great! 
Happy new year Hugo

**Comment by HugoGiraudel** [comment]
Happy New Year to you too Emily. :) :tada:
