### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Grawl** [HugoGiraudel/sass-guidelines#286]
I create this issue for questions and disqussions related only to russian translation, okay?

**Comment by Grawl** [comment]
Now I am updating russian translation from `1.0.0` to `1.2.0` and have some questions to new content.

In this paragraph:

> I also happen to be the author of a book about CSS (in French) entitled [CSS3 Pratique du Design Web](http://css3-pratique.fr/) (*Eyrolles* editions), as well as a book about Sass (in English) entitled [Jump Start Sass](https://learnable.com/books/jump-start-sass) (*Learnable* editions).

Two words are not clear enough for me: “Eyrolles” and “Learnable”. @HugoGiraudel please describe this.

**Comment by morkro** [comment]
These seem to be publisher editions or something like that. 

[Eyrolles editions](http://www.editions-eyrolles.com/) and [Learnable](http://learnable.com) (Now Sitepoint Premium).

**Comment by HugoGiraudel** [comment]
What @morkro said. :)

**Comment by Grawl** [comment]
Oh it'untranslateable names. Got it.

**Comment by HugoGiraudel** [comment]
@Grawl Do you need me to find another Russian translator to assist you? Is @PavelDemyanenko still in the loop?

**Comment by Grawl** [comment]
@HugoGiraudel it will be good.

**Comment by PavelDemyanenko** [comment]
@Grawl Я могу помочь, только направь на какую часть мне надо подключиться

**Comment by Grawl** [comment]
Я сейчас занимаюсь переносом изменений из 1.2 в текущую редакцию, довольно муторно. Прямо сейчас заканчиваю `_syntax.md` – иду по оглавлению в `_includes/chapters.html`.
Делаю так:
- открываю историю изменений англоязычного файла
- изменения начиная с даты 12.04.15 переношу снизу-вверх (от старых) в файл русского перевода
Там надо ещё переносить сниппеты в отдельные файлы, например. Работы куча.

**Comment by PavelDemyanenko** [comment]
Хорошо, сейчас склоню репу и буду разбираться и отпишу, что возьму в работу 🙏🏻

**Comment by Grawl** [comment]
Пока нас двое – можешь начать с конца тот порядок, что взял я.

**Comment by Grawl** [comment]
Я буду отправлять все свои изменения, которые буду коммитить, как только смогу, чтобы нам не делать одно и то же.

**Comment by PavelDemyanenko** [comment]
А пушни свою ветку и может пулл-реквест создадим типа работа в процессе и всё такое?

**Comment by Grawl** [comment]
Можно.

**Comment by Grawl** [comment]
Но как будет выглядеть всё это от нас обоих? Два запроса слияния?

**Comment by PavelDemyanenko** [comment]
Я буду в твою ветку коммитить, а ты делай пулл-реквест

**Comment by Grawl** [comment]
Это надо тебе дать доступ в мой форк?

**Comment by PavelDemyanenko** [comment]
Всё-всё понял, сейчас твою репу склоню, в какой ветке ты там работаешь?

**Comment by Grawl** [comment]
`gh-pages`

**Comment by Grawl** [comment]
Запрос создан https://github.com/HugoGiraudel/sass-guidelines/pull/295

**Comment by PavelDemyanenko** [comment]
👍🏻👍🏻👍🏻

**Comment by Grawl** [comment]
Старайся отправлять любую даже не завершённую работу, чтобы я с каждым новым подходом к работе мог знать, за что стоит браться, а за что – нет.

**Comment by Grawl** [comment]
@PavelDemyanenko ну что там у тебя? Я большинство работы сделал сейчас, надо теперь крупные куски текста переводить. Я в следующий раз могу начать вычитку существующего материала, но могу и переводить, если у тебя нет времени.

**Comment by PavelDemyanenko** [comment]
@Grawl да пока что почитал, посмотрел объем работ на выхах, я планирую сегодня вечером, часов в 11 по Москве приступить.

**Comment by Grawl** [comment]
Ну, смотри запрос – я там все изменения перенёс, уже не надо смотреть по истории изменений английских версий глав. Осталось переводить.

**Comment by redgarnet** [comment]
Ребята, там синтаксическая ошибка в главе "О Sass"
"Sass — это расширение CSS, которое добавляет силу и **элигантность** к основному языку."

**Comment by redgarnet** [comment]
Ну реально глаз режет.
Глава "Ключевые принципы"
2-й абзац.
Спасибо моим глупым **эскпирементам**,

**Comment by Grawl** [comment]
@redgarnet благодарю! Внесу в обновление. (Всё никак руки не дойдут довести дело до конца.)

**Comment by nastiatikk** [comment]
Привет, ребята!
У меня есть время помочь с переводом. По комментариям я вижу, что работа уже идет во-всю. Поэтому дабы случайно не хвататься за то, что уже сделано или уже в процессе перевода, скажите какие главы я могу взять на себя?

**Comment by nastiatikk** [comment]
Ok, берусь за часть introduction

**Comment by Grawl** [comment]
погоди, обновляю инструкции

**Comment by Grawl** [comment]
Итак, привет. Тут надо смотреть в https://github.com/HugoGiraudel/sass-guidelines/pull/295, как ты уже видишь, и делать как я делал там.

Сейчас сложность в том, что я не закончил `1.2` до выпуска `1.3`.

Чтобы не переводить тот текст, который мог быть в `1.2`, но был удалён из `1.3`, нужно сначала перенести все изменения из английской `1.3` в русскую `1.2`. И потом уже браться за задачу перевода нового содержимого.

**Comment by nastiatikk** [comment]
Ок, наверное такой вопрос уже сто раз спрашивали, но я спрошу еще раз :)
Если я возьму главу 1.3 и начну переводить ее напрямую из английской 1.3 в русскую 1.3 (сравнивая предложение с предложением и абзац с абзацем) дело не пойдет быстрее?

**Comment by Grawl** [comment]
Да, ты можешь перевести всё с нуля. Но так дело не пойдёт быстрее, ведь `1.3` – это десяток-другой изменений, а весь Sass Guidelines – это довольно много, причём есть некоторые волевые решения по переводу – вроде соглашений – например, что-то из английского заимствовать, а что-то называть русскими словами.

**Comment by nastiatikk** [comment]
Ок, ясно

Я правильно понимаю, что версия 1.3 еще не была перенесена даже частично в 1.2? Если нет, то где можно увидеть прогресс переноса изменений из 1.3 в 1.2? #295 **Translate new content** checkbox о переводе, а не о внесении изменений, правильно?

**Comment by nastiatikk** [comment]
И еще вопрос – с чего мне делать ветку, если в #295 конфликт?

**Comment by Grawl** [comment]
> Я правильно понимаю, что версия 1.3 еще не была перенесена даже частично в 1.2?

Да, никто за это ещё не брался.

> Translate new content checkbox о переводе, а не о внесении изменений, правильно?

“Перевести новое содержимое” означает перевод, не перенос.

> И еще вопрос – с чего делать ветку, если в #295 конфликт?

Я в последний раз делал ветку с оригинала.

**Comment by Grawl** [comment]
Конфликт там после выпуска `1.3` появился, если не ошибаюсь.

**Comment by HugoGiraudel** [comment]
Hey guys. If I can do anything to assist you, please tell.

**Comment by HugoGiraudel** [comment]
I’ll open this back when someone starts working again on the Russian translation.
