### ISSUE TITLE
Offline caching

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#288]
Given how Sass Guidelines is a single long text document, I can only assume some people would like to save it as a read for their flight, where they have not much to do. Therefore it would be nice if we could use some application cache to make the reading experience available offline.

**Comment by mxstbr** [comment]
Will do!

**Comment by HugoGiraudel** [comment]
Sweet! Feel free to open a PR against `gh-pages`. :)

**Comment by morkro** [comment]
It's basically only the different language versions, right? :)
The rest of the website is one file anyway and there is no routing or something the like.

**Comment by HugoGiraudel** [comment]
Yep. We should be caching all the languages, that's it. :)

**Comment by mxstbr** [comment]
And the assets, stylesheets, javascript etc., right?

**Comment by gr2m** [comment]
check out PouchDB.com’s setup, also https://github.com/gr2m/appcache-nanny/ might be helpful.

**Comment by HugoGiraudel** [comment]
Yep, we need to cache the assets as well. Basically, we need to cache what is needed so that the site is usable while offline.

**Comment by mxstbr** [comment]
Did it by hand, see #290
