### ISSUE TITLE
Offline support with Service Workers

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#297]
This issue is a follow-up from #290. The AppCache specification has been deprecated and therefore should not be used to ensure offline support. Service Workers should be used instead. Heads up from: https://twitter.com/voxpelli/status/687661940726984704.

Support charts for Service Workers: https://jakearchibald.github.io/isserviceworkerready/.
Offline Cookbook by Jake Archibald: https://jakearchibald.com/2014/offline-cookbook/.

Currently wondering:
- Is there anything preventing us from implementing a Service Worker solution in the current setup (Jekyll, Github Pages in safe mode, no-JavaScript experience ensured, etc.)?
- Do we have to remove Appcache implementation or can we keep both concurrently? 

Ping @mxstbr as he was interested in working on this.

**Comment by mxstbr** [comment]
We can keep both for now, the main thing is that ServiceWorker only works for HTTPS connections. Is Sass guidelines available over HTTPS, and can we force browsers to connect via HTTPS with Github Pages?

**Comment by mxstbr** [comment]
I'll add a ServiceWorker anyway, probably today in the evening, and we can look at the HTTPS thing when time permits!

**Comment by HugoGiraudel** [comment]
I have not been able to point to a valid resource stating that Service Workers will only work with a secure connection. Do you have anything on topic?

**Comment by mxstbr** [comment]
[Any of these links](https://www.google.at/search?q=ServiceWorker+httos&oq=ServiceWorker+httos&aqs=chrome..69i57j0l3j69i61.1099j0j4&sourceid=chrome-mobile&ie=UTF-8#safe=off&q=ServiceWorker+https) 

it's in the spec, because a ServiceWorker is basically a MITM, allowing that to run over HTTP would be a major security risk.

**Comment by HugoGiraudel** [comment]
Oh. True. Alright. Well, I suppose some research about HTTPS over GitHub Pages would be needed. Depending on costs and complexity, I can only consider moving Sass Guidelines to a different environment if really needed

**Comment by mxstbr** [comment]
I think the only way to get it to HTTPS is putting Cloudflare in front of it. That'll work, is free and we can force-redirect to HTTPS.

**Comment by HugoGiraudel** [comment]
That sounds legit.

**Comment by HugoGiraudel** [comment]
Blocked until #362 gets resolved.

**Comment by HugoGiraudel** [comment]
@morkro and I will try to take over this and make it work. :)

**Comment by HugoGiraudel** [comment]
Started in #298.

**Comment by morkro** [comment]
New development branch: [`feature/offline-support`](https://github.com/HugoGiraudel/sass-guidelines/tree/feature/offline-support)

**Comment by morkro** [comment]
This has finally been merged in #399 🎉
