### ISSUE TITLE
 Shade icon color - Accessibility audit - color/contrast

### ISSUE THREAD

**Issue by innovandrew** [HugoGiraudel/sass-guidelines#303]
96 items failed contrast tests.

All 96 items are icons - specifically the link icon beside each heading. Shading the color ~15% will resolve.

I have determined that all other items exceed passing requirements, achieving "AA" grade. Excellent work!

**Comment by HugoGiraudel** [comment]
Wow, that’s great! Thank you so much. Regarding the icon, I don’t actually choose the color as it is a unicode glyph, so I think the best would be to move to a SVG icon maybe? What do you think?

**Comment by innovandrew** [comment]
If it's a glyph the color should be able to be controlled with the "color" property.

Glyph icons themself come loaded with accessibility concerns. If you ask me, so do SVG icons. Which one to use depends on purpose of the use. I'll go over this with you.

I'd say if your other icons are SVG, might as well make this one too.

**Comment by HugoGiraudel** [comment]
Other icons are SVG, however this one is being injected by JavaScript, and manipulating SVG with JavaScript is quite a pain in the ass as far as I can tell.

**Comment by HugoGiraudel** [comment]
Should be fixed. @innovandrew, could you check? :)
