### ISSUE TITLE
Feature ideas for a multipage approach

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#307]
The idea of this ticket is to collect all possible ideas for a revamp of the site’s architecture.

## Pros

- More flexibility for chapter pages (better layout for extra readings, possibly comments, inner table of contents, etc.)
- Smaller navigation (only top level chapters)
- Possibility for a “seen” check mark for visited navigation items (similar to how it's done on the [Redux](http://redux.js.org/index.html) website)
- Possibility for a “new content” mark for navigation items to make it easier for the user to see changes

## Cons

- Harder for browser search
- Reading is interrupted by page change

*Edit: updated by @HugoGiraudel.*

**Comment by HugoGiraudel** [comment]
I have been thinking of moving Sass Guidelines to a multiple pages website has for a while now. This document has gotten so big that I think like it would make sense. I even have some ideas for the design. The idea would be to have one page per chapter.

My biggest question right now would be: how would we handle URLs?

* Language first, then chapter (e.g. `/fr/comments/`)
* Chapter first, then language (e.g. `/comments/fr`)
* Do we translate URLs (e.g. `/fr/commentaires/`)

**Comment by morkro** [comment]
Translated URLs sounds good at first, but could be a mess to maintain?

My personal favourite is chapter first, then language: `/syntax-formatting/strings/de`. By that each sub-page contains all translated versions, and it's easier to work with.

**Comment by HugoGiraudel** [comment]
Maybe simple redesigning it a bit to have a fixed sidebar would be enough:

<img width="1440" alt="screen shot 2016-01-28 at 23 11 31" src="https://cloud.githubusercontent.com/assets/1889710/12660557/9780f044-c614-11e5-87da-ae48a76b533a.png">

**Comment by HugoGiraudel** [comment]
Alright. Nope. 

But I have a redisngon the way. ;)
