### ISSUE TITLE
Improve the section about extend

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#31]
See #28.

**Comment by HugoGiraudel** [comment]
@iamcarrico, I rewrote the `@extend` section. Would you mind giving me your opinion perhaps?

http://sass-guidelin.es/#extend

**Comment by iamcarrico** [comment]
First off, you quoted Bieber and attributed it to Beyoncé. For that, I have this:

> *[If you quote Bieber and attribute it to Beyoncé]*, you're going to burn
> in a very special level of hell. A level they reserve for child molesters
> and people who talk at the theater.
> — Shepherd Book

This is your guide, and thus you should have the final say. I still disagree with your thesis, but as you state at the beginning, it is an "opinionated styleguide". 

As a note, I was just chatting with @elyseholladay who gave me some of the research of @drewwells that supported a suspicion I had about gzip. Although a deeper explanation can be found [here](http://www.gzip.org/deflate.html), the gzip thesis can only be supported if all non-dynamic code is put together and file sizes are less than 32kb. If either of these are not true, then extra bloat will be added to the codebase. Now, how much and what is worth— I am not sure and would have to do some more practical tests. But I can say that I would still rather use @extend.

**Comment by drewwells** [comment]
The rewritten sections looks great!

For more info... Gzip looks at files in 32kb blocks, so you still get benefits beyond 32kb.  However, a 40kb file still benefits from compression. The code to be compressed must be in either the first 32kb or the last 8kb.  Code crossing the boundary won't benefit from compression.

I'm with @HugoGiraudel about @extend. It provides some minor code optimizations but introduces a lot of headaches and novice users should be warned. It works well for very simple cases, but scaling @extend is tricky. I find more often that developers hang themselves from using it. @extend feels like a booby trap masquarading as composition/inheritance.

**Comment by HugoGiraudel** [comment]
> First off, you quoted Bieber and attributed it to Beyoncé.

Fixed: http://sass-guidelin.es/#extend.

Interesting points you both in any case. I think I am cool with the current version of the `@extend` section. Let me close this if you don't any more objection.
