### ISSUE TITLE
Add something about namespaces

### ISSUE THREAD

**Issue by crswll** [HugoGiraudel/sass-guidelines#34]
I'd like to suggest prefixing variable names with a namespace(?) whenever possible. This makes auto-complete a lot more useable, especially for things that can end up with weird names like colors and breakpoints. It can save trips to other files as well. Yes, I am that lazy.

``` scss
$color--sass-pink: hsl(330, 50%, 60%);
$color--theme-primary: $color-sass-pink;

$breakpoint--narrow: 767px;
$breakpoint--wide: 900px;

**Comment by HugoGiraudel** [comment]
Namespace! Good stuff. I'll add something about that.

**Comment by HugoGiraudel** [comment]
I added something about namespaces. :)

**Comment by crswll** [comment]
Sweeeeet.
