### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#344]
Sass Guidelines still does not have a license. The code from the Sass Guidelines should be licensed under MIT.

However the content has to use another license given it’s not a software. [ChooseALicense](http://choosealicense.com/non-software/) says: 

> **Mixed Projects**
> If your project contains a mix of software and other material, you can include multiple licenses, as long as you are explicit about which license applies to what parts of the project. See the license notice for this site as an example.

Their [README](https://github.com/github/choosealicense.com/blob/gh-pages/README.md) for instance states:

> The content of this project itself is licensed under the [Creative Commons Attribution 3.0 license](http://creativecommons.org/licenses/by/3.0/us/deed.en_US), and the underlying source code used to format and display that content is licensed under the [MIT license](http://opensource.org/licenses/mit-license.php).

Any thought? Maybe [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en_US)?

**Comment by morkro** [comment]
The _CCA 3.0_ license seems to be specified for the United States? At least this is what I get out of the link.

I would suggest the [Creative Commons Attribution 4.0 International license](http://creativecommons.org/licenses/by/4.0/) then.

**Comment by HugoGiraudel** [comment]
Done with https://github.com/HugoGiraudel/sass-guidelines/commit/465037c305b302583436fe3013bbf6cf8348abf2.
