### ISSUE TITLE
Only lengths can omit the unit

### ISSUE THREAD

**Issue by chriseppstein** [HugoGiraudel/sass-guidelines#35]
> Zero is zero, no unit involved.

In CSS, only lengths can legally omit the unit. So this is not true for the `<angle>`, `<time>`, `<frequency>`, nor `<resolution>` numeric types. See: http://www.w3.org/TR/css3-values/#lengths for the note that says that lengths can be unit-less when `0`. that note is not present for other types.

**Comment by HugoGiraudel** [comment]
I'll fix it right away. :)
