### ISSUE TITLE
Пропустили букву

### ISSUE THREAD

**Issue by Meshock** [HugoGiraudel/sass-guidelines#353]
Цветовые форматы

... цветовых форматов:

Ключеые слова CSS;  <----- буква В
Обозначение HSL;

**Comment by HugoGiraudel** [comment]
Hello there. I am the main author of this project, unfortunately I don’t speak a single word of Russian. Do you feel like you could provide your issue in English? Else, could one of our lovely Russian team give me a hand with this?

Ping @grawl, @PavelDemyanenko, @nastiatikk.

**Comment by nastiatikk** [comment]
@HugoGiraudel the issue is with a misspelled word - a letter is missing in the word **Ключеые**. Should be **Ключевые** (with **в** in the middle).

**Comment by HugoGiraudel** [comment]
Do you feel like you could submit a PR to fix it maybe?

**Comment by nastiatikk** [comment]
Sure, will try to do it on a week!
