### ISSUE TITLE
color-formats: some contradiction

### ISSUE THREAD

**Issue by dryoma** [HugoGiraudel/sass-guidelines#357]
Hi!

[This chapter](https://sass-guidelin.es/#color-formats) gives an order of preference for color formats. While Hex is in the bottom of this list, it is still allowed. Yet the example below that states that it is not, thus contradicting the former:

```
// Nope
.foo {
  color: #FF0000;
}
``` 

I'd like to ask rephrasing the comment there, e.g. to `Possible, but the above are preferred`.

The thing is, my teammates and I are thinking of a Sass styleguide to adopt. I get it that Sass Guidelines is *not a codestyle* technically, yet I really like it for the most part, and am going to implement in a config for [stylelint-scss](https://github.com/kristerkari/stylelint-scss/) (when it's ready to ship). But my teammates are confused by this particular contradicion (yeah, we kinda take a serious approach :) ).

**Comment by HugoGiraudel** [comment]
Wishes are order: https://github.com/HugoGiraudel/sass-guidelines/commit/f8f32ba436f9a1c129ae632472c779cd9a8ce8b1. :)

**Comment by dryoma** [comment]
Great, thanks!
