### ISSUE TITLE
"Do not use lighten or darken"

### ISSUE THREAD

**Issue by chriseppstein** [HugoGiraudel/sass-guidelines#36]
> To lighten or darken a color, do not use lighten and darken Sass functions.

these functions manipulate the `lightness` value of a color in the HSL space by adding or removing lightness. These are convenience aliases for `adjust-color($lightness: -10%)`. Note that `scale-color($lightness: 10%)` changes the lightness `10%` towards the end point. Mix does this but in a way that can change the hue and saturation. Maybe that's what people want... but it seems bad to just tell them "don't use these functions".

**Comment by HugoGiraudel** [comment]
My point was not to forbid the use of `darken` and `lighten` but to warn against their behaviour that might be surprising. I'll add your explanation so people can choose wisely.
