### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by douglasdeodato** [HugoGiraudel/sass-guidelines#361]
Hi all,

We are creating this thread to update and finalize the pt-br version of sass-guidelines.

the old thread you can find here: https://github.com/HugoGiraudel/sass-guidelines/issues/162#issuecomment-238854315

myself and @jhonnymoreira will be working on this new update and translation and after this finally the Brazilian community will use the benefits of this project.

We need Help, if you want help us, please comment on this thread :)

We had created a Trello board to have a better communication between us: https://trello.com/b/w9yUFyIs  

if you have any questions let us know.

Thank you.

**Comment by HugoGiraudel** [comment]
Out of curiosity, are you guys still working on this? :)

**Comment by douglasdeodato** [comment]
hey @HugoGiraudel  sorry man about this, I started work on this with the other guy but he Disappeared :), anyway probably I will start from scratch again, sorry about this. thank you.

**Comment by HugoGiraudel** [comment]
I’m going to close this. :)
