### ISSUE TITLE
getter functions and maps

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-guidelines#366]
Hi, Hugo!

Getter functions ant their maps should be on `abstracts/functions` or `abstracts/variables`? Considering this case:

```sass
/// Z-indexes map, gathering all Z layers of the application
/// @access private
/// @type Map
/// @prop {String} key - Layer’s name
/// @prop {Number} value - Z value mapped to the key
$z-indexes: (
  'modal': 5000,
  'dropdown': 4000,
  'default': 1,
  'below': -1,
);

/// Get a z-index value from a layer name
/// @access public
/// @param {String} $layer - Layer’s name
/// @return {Number}
/// @require $z-indexes
@function z($layer) {
  @return map-get($z-indexes, $layer);
}
```

Being the maps private variables, which should start with `_`, they and their getter functions should stay close to each other.

My bet is on both function and map on `abstracts/variables`. What you think?

Thank you for your attention.

**Comment by robsonsobral** [comment]
Another example:

```sass
/// Friendlier colour names with Sass maps
$_color-base-grey: rgb(229, 231, 234);

/// @prop {String} keys - Keys are identifiers mapped to a given length
/// @prop {Map} values - Values are pure colors or the returned value of functions
$_palettes: (
	'purple': (
		'base': rgb(42, 40, 80),
		'light': rgb(51, 46, 140),
		'dark': rgb(40, 38, 65)
	),
	'grey':  (
		'base': $_color-base-grey,
		'light': tint($_color-base-grey, 10%),
		'dark': shade($_color-base-grey, 10%)
	)
);

/// @access public
/// @param {String} $palette - Palette name
/// @param {String} $tone - tone name
/// @require {String} $palette
/// @link http://erskinedesign.com/blog/friendlier-colour-names-sass-maps/
@function palette($palette, $tone: 'base') {
	@return map-get(map-get($_palettes, $palette), $tone);
}
```

**Comment by HugoGiraudel** [comment]
I’d put the map in `_variables.scss`, the function in `_functions.scss`, but I totally can see why you would do otherwise. The reason why I would split them, is because you are unlikely to update them both at the same time.

Either you want to check the existing —let’s say— colors, and you need to update the map, which would be searched in the variables file. Or you want to see how the function works, and then you would look it up in the functions file.

**Comment by robsonsobral** [comment]
It's the SCSS lint which pointed me this issue.

Yeah, isn't probable I update both at the same time, but isn't rare I want to read both at the same time: "why this bug happened?", "what am I missing?", etc, etc...

Sass really needs a shorter syntax to get a map value.

Thank you, Hugo!

**Comment by HugoGiraudel** [comment]
> Sass really needs a shorter syntax to get a map value.

I highly disagree. :)
