### ISSUE TITLE
@import list formatting

### ISSUE THREAD

**Issue by MichaelArestad** [HugoGiraudel/sass-guidelines#37]
This is likely something that comes down to preference, but I usually prefer import lists to look something like this:

```SCSS
@import "vendors/bootstrap",
  "vendors/jquery-ui";

@import "utils/variables",
  "utils/functions",
  "utils/mixins",
  "utils/placeholders";

@import "base/reset",
  "base/typography";

@import "layout/navigation",
  "layout/grid",
  "layout/header",
  "layout/footer",
  "layout/sidebar",
  "layout/forms";

@import "components/buttons",
  "components/carousel",
  "components/cover",
  "components/dropdown";

@import "pages/home",
  "pages/contact";

@import "themes/theme",
  "themes/admin";
```

And (I've not tested this), but maybe even:

```SCSS
@import
  "components/buttons",
  "components/carousel",
  "components/cover",
  "components/dropdown";
```

**Pros**
* Easier to scan
* Very obvious sections

**Cons**
* Can be slightly more annoying to add/remove the last item because the semocolor needs to be relocated.
* ??

**Comment by Keats** [comment]
I don't find the first one very readable but the second one looks very good.
Overall I still prefer commenting/adding/removing/moving lines easily, so the one currently recommended   still wins for me.

**Comment by MichaelArestad** [comment]
Adding/removing/commenting is still just as simple with the exception of the last item. For some reason, repeating `@import` over and over just feels like visual clutter to me.

**Comment by HugoGiraudel** [comment]
Nope on the first. Perhaps on the second, although I am really not convinced at this point Michael.

**Comment by MichaelArestad** [comment]
Neither am I, to be honest as the gains are pretty marginal. I do think it's worth a little discussion, though.

**Comment by sturobson** [comment]
I've started going with 'number 2' as it just saves a little bit of time writing it out. Tabbing (where my IDE creates spaces) is quicker than writing @import on every line. 
In terms of gains: There's better readability as you can concentrate on the files you're pulling in as you're not laboured with @import everywhere and if you've a long manifest of imports it'd be a lot easier. in my most humblest of opinions.

**Comment by HugoGiraudel** [comment]
I like the second version as well. I might consider switching to it.
