### ISSUE TITLE
Suggestions from the old Recess

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-guidelines#373]
Hi, Hugo.

May I suggest you to include something from the old Recess?

> - **noJSPrefix** - Don't style `.js-` prefixed classnames

We should avoid to style js classNames, like `js-` and `trigger-`.

Thank you!

**Comment by HugoGiraudel** [comment]
Agreed, but Sass Guidelines do not concern themselves with CSS guidelines, only Sass specific ones. :)
