### ISSUE TITLE
Ubuntu - Can't open panel option 

### ISSUE THREAD

**Issue by yoanmalie** [HugoGiraudel/sass-guidelines#374]
I'm unable to open the right panel options even if i click on the settings button or the button in the intro.

Firefox 50.1.0
Chrome 54.0.2840.100 (64-bit)

Ubuntu 16.04

**Comment by HugoGiraudel** [comment]
Do you have a JavaScript error?

**Comment by robsonsobral** [comment]
Same thing here, on Firefox 52 and MacOS 10.11.6.

Together with a strange horizontal scrollbar.

**Comment by morkro** [comment]
Looks like the JavaScript file isn't loaded.

**Comment by HugoGiraudel** [comment]
I think that should be fixed…?

**Comment by morkro** [comment]
Looks like that fixed it! :) Works for me.

**Comment by HugoGiraudel** [comment]
Excellent. We really need to get #297 going.
