### ISSUE TITLE
Selector nesting in mixins

### ISSUE THREAD

**Issue by Keats** [HugoGiraudel/sass-guidelines#40]
How do you handle descendants in mixins?  

For example, this mixin creates media objects (image on one side, text on the other): https://github.com/Keats/snowflake/blob/master/components/_media-object.scss and needs to set some values on the nested items in addition to itself.  

How would you do that without nesting the 2 selectors in the normal case and the --reverse case?

EDIT: I should mention I use libsass and there's no at-root that I could use I guess

**Comment by HugoGiraudel** [comment]
I think this is a fairly specific case where nesting makes sense. You should not be concerned that much with this *no nesting* rule.

**Comment by Keats** [comment]
Yeah that's what I thought.

Thanks !
