### ISSUE TITLE
Add tracking pixel to Service Worker

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#400]
While offline, Google Analytics can't be fetched anymore.

**Comment by HugoGiraudel** [comment]
That’s a good idea. Do you feel like you could tackle this @morkro?

**Comment by morkro** [comment]
Sure thing!

**Comment by HugoGiraudel** [comment]
Pïng @morkro. If you ever want to do that. If you have a resource on this matter, I can have a look.

**Comment by HugoGiraudel** [comment]
Fuck tracking.
