### ISSUE TITLE
Zeros

### ISSUE THREAD

**Issue by indrekpaas** [HugoGiraudel/sass-guidelines#45]
In the [Zeros](http://sass-guidelin.es/#zeros) section it's said "Numbers should display leading zeros before a decimal value less than one."

On the contrary, the TL;DR section at the bottom recommends "No leading or trailing 0;"

**Comment by thibaultCha** [comment]
Not sure about this one, but the colors session says:

```
color: rgba(0, 0, 0, .1); // so should this be 0.1?
```

**Comment by HugoGiraudel** [comment]
Both fixed.
