### ISSUE TITLE
Broken link in Media Queries Usage sub section

### ISSUE THREAD

**Issue by deerawan** [HugoGiraudel/sass-guidelines#453]
# Location
**Section**
Responsive Web design and breakpoints

**Sub-section**
Media Queries Usage

# Issue
Link for `tests have been made` is broken

![image](https://user-images.githubusercontent.com/1243921/78756775-afe52a80-79be-11ea-8cb2-0719cf358a33.png)

When it is clicked, it goes to https://sasscast.tumblr.com/post/38673939456/sass-and-media-queries but it displays

![image](https://user-images.githubusercontent.com/1243921/78756862-db681500-79be-11ea-9da2-d66eb2de658b.png)

**Comment by HugoGiraudel** [comment]
Thank you for the heads up. Fixed with https://github.com/HugoGiraudel/sass-guidelines/commit/845a3389afaeec24aee4e4bc9642f88639fa1519.
