### ISSUE TITLE
More than one css file 

### ISSUE THREAD

**Issue by JelteF** [HugoGiraudel/sass-guidelines#46]
The current architecture compiles to onegigantic css file that contains the css for all pages. For a website bigger than a 3 page site this is a crazy structure. What you want is one css file for the main layout and another (small one) for every page that needs extra css. This way selectors can't collide and it doesn't download all css when you just need the homepage.

**Comment by HugoGiraudel** [comment]
I have run some tests at work, and as far as I can tell it is still better to have one big file that is being cached on first page, than having a specific file for each page which is likely to never be present in the browser's cache.

**Comment by elyseholladay** [comment]
@HugoGiraudel maybe on smaller projects. In both my current role at RMN and my previous job (enterprise app), it made WAY more sense to have a globals that was cached, and then individual CSS files for pages/apps. At RMN, our store page HAS to perform, so it's SIGNIFICANTLY faster to have a store page CSS file and not include any of the rest of the site's CSS (which is a lot). 

This is definitely your style guide and therefore your opinions, but I think if you want to write a more general guidelines/explanation site, than it's worth mentioning other styles/opinions, such as this.

**Comment by jamadam** [comment]
@HugoGiraudel
I'm a fan of splitting CSS output into per page basis. It's only a sake of separation of concerns and not for performance.

Although, since most of your guidlines convinces me a lot, I'm thinking twice if I'm wrong. So let me ask, how do you think about name collisions between pages?

**Comment by HugoGiraudel** [comment]
@elyseholladay Thank you for your opinion Elyse. Be sure I'll consider adding something about this in the styleguide.

@jamadam The problem with splitting CSS into different pages is you force yourself into code duplication. What if a module exists in two pages? Will it be output twice? This is the reason we don't think a GUI in a matter of pages but as components.

**Comment by jamadam** [comment]
@HugoGiraudel 
Well, I'm not talking about performance but maintenability. I'm just curious how you deal with naming css classes in huge namespace. It maybe beyond the sass topic, though.

Talking about duplication of modules, I haven't been caring much. Actually, I restrict my own modules to output nothing at @import so duplication would be limited. I compromise on clearfix appearing hundreds of csses for narrowing each namespace.

Actually, I manage 300 html templates and scss endpoints for single application without duplication in codebase. I'm considering if I should merge them into fewer csses by converting page names into selector and there must be an additional naming convention.

**Comment by HugoGiraudel** [comment]
> I'm just curious how you deal with naming css classes in huge namespace. It maybe beyond the sass topic, though.

I'm not sure I do anything special. Never had an issue until now. :)

**Comment by jamadam** [comment]
@HugoGiraudel Thanks :)

**Comment by HugoGiraudel** [comment]
I am not keen on tackling this issue in the guidelines I must say. I feel like large enough projects that cannot use a single file for whatever reasons have good enough architects who do not need a guide to deal with this. It might be a quick assumption but it is one I am willing to make.
