### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by IAfanasov** [HugoGiraudel/sass-guidelines#460]
Quote:
```
A recent study shows that using CSS Comb (which uses type ordering) for sorting CSS declarations ends up shortening the average file size under Gzip compression by 2.7%, compared to 1.3% when sorting alphabetically.
```

The link to `recent study` is dead. And the year 2014 in the link says that it is not that recent study

**Comment by morkro** [comment]
Either we

- Remove the reference to study and rewrite sentence (requires all other translations to be updated as well)
- Replace the link with WebArchive: https://web.archive.org/web/20190618180712/http://peteschuster.com/2014/12/reduce-file-size-css-sorting/ (quickest)
- Find a similar study to replace the link with (a quick search shows plenty of articles on that topic)

Wdyt @HugoGiraudel ?

**Comment by HugoGiraudel** [comment]
I think using an internet archive link is probably a good idea. :)

**Comment by morkro** [comment]
I did that quickly and opened a PR

**Comment by morkro** [comment]
Closing this issue as it has been resolved for now  :)
