### ISSUE TITLE
More clearly indicate how unit interpolation works

### ISSUE THREAD

**Issue by scottkellum** [HugoGiraudel/sass-guidelines#54]
In the [unit section](http://sass-guidelin.es/#units) it states how to properly add a unit to a unitless number but doesn’t say why it works that way. This is a particular point of confusion for many newcomers to Sass who assume units can be treated like strings. These values are not strings and have meaning. Showing people that units behave like algebraic symbols is important to understanding and manipulating them in Sass.

**Comment by HugoGiraudel** [comment]
That is a fair point Scott. I'll add extra information. :)

**Comment by HugoGiraudel** [comment]
What do you think now @scottkellum: http://sass-guidelin.es/#units?

**Comment by scottkellum** [comment]
@HugoGiraudel Looks good. Note that `+ 0px` behaves a bit differently and will not convert another compatible unit.

`0px + $value` is more robust because

`1in + 0px` = `1in`
while
`0px + 1in` = `96px`

idk, maybe that gets into the weeds a bit. For a simple guide like this I’d probably just recommend `$length: $value * 1px;` and omit `$length: $value + 0px;`

**Comment by HugoGiraudel** [comment]
Actually I like that. I might add it. :)
