### ISSUE TITLE
'element' isn't a realistic class name

### ISSUE THREAD

**Issue by mikemaccana** [HugoGiraudel/sass-guidelines#55]
`.element` is used as an example SASS rule.

Naming classes either 'element' (vague) or after an element (eg '.p' - redundant, there is already an element for that) is generally considered poor. 

These examples should be either `elementName` or `className`

**Comment by HugoGiraudel** [comment]
`.element` is only used as an example. `.elementName` is not respecting hyphen-delimited naming conventions. Perhaps `.element-name` ?

**Comment by mikemaccana** [comment]
Acknowledged re: dash-delimited. Either `element` or `class-name` would be fine.

**Comment by tobysteward** [comment]
I reckon `.foo` would probably be better

**Comment by HugoGiraudel** [comment]
Agreed on `.foo`.

**Comment by mikemaccana** [comment]
`.class-name` is more descriptive than `.foo`, but `.foo` is still better than `.element`

**Comment by tobysteward** [comment]
Not a bad suggestion but `.class-name` isn't as readable as `.foo` and `.foo` has become sort-of a standard as the metasyntactic variable ([reference](http://en.wikipedia.org/wiki/Metasyntactic_variable).)

**Comment by mikemaccana** [comment]
lole @tobysteward I know what a metasyntactic variable is! `.class-name` provides an adequate description of what should be there, `foo` does not. But hey, this is already taking far too much discussion for what should be a simple fix.

**Comment by tobysteward** [comment]
Sorry, I didn't mean to sound condescending - I was just adding some substance to my suggestion for those (perhaps uninformed) checking in on the issue.

**Comment by mikemaccana** [comment]
👍
