### ISSUE TITLE
Make crystal clear this isn't an official styleguide

### ISSUE THREAD

**Issue by Snugug** [HugoGiraudel/sass-guidelines#59]
Hey Hugo,

I really appreciate the effort you've put in to create this, I personally know how much effort it takes to write something as comprehensive as this and applaud your effort. That being said, this looks very official, it's copy is very official sounding, and you put enough stuff out into the world that people may think it's official. The disclaimer is too hidden, it should be much further towards the top; maybe have the tagline be something like "An opinionated styleguide for writing sane, maintainable and scalable Sass." This is especially true for your Architecture section which is not just highly opinionated, but is likely to not be a good fit depending on the compiler/CSS architecture/build system someone is using.

**Comment by HugoGiraudel** [comment]
> An opinionated styleguide for writing sane, maintainable and scalable Sass.

That sounds like a decent request. :)

**Comment by HugoGiraudel** [comment]
Baseline updated, and I added a note to the architecture section. :)
