### ISSUE TITLE
Is 'SCSS not Sass' really required?

### ISSUE THREAD

**Issue by tobysteward** [HugoGiraudel/sass-guidelines#68]
I think the guidelines would benefit from supporting both SCSS and Sass syntax. 

As a `.sass` user (and proponent) I don't think we should disregard either as both are a core feature/offering of the language and therefore a feasible choice for each end user. 

Maybe doing something like the [Sass Docs](http://sass-lang.com/guide) and offering a toggle page wide would be wise.

**Comment by HugoGiraudel** [comment]
> Maybe doing something like the Sass Docs and offering a toggle page wide would be wise.

I would love that, although that would require a significant development that I am not willing to engage. I'd gladly merge any solid PR about this though.

**Comment by HugoGiraudel** [comment]
Done, actually.

**Comment by tobysteward** [comment]
Oops! I already had written some code for it (https://github.com/tobysteward/sass-guidelines/commit/538830bdfd4021dc82188795961be2997886d396) but hadn't had a chance to PR!

I like your approach, my mind went straight to JS, yours went to CSS :+1:

**Comment by HugoGiraudel** [comment]
Oh. Please accept my apologies. I should have told you when I started implementing the feature.

**Comment by tobysteward** [comment]
Don't worry - I think I probably should have said something too :)
