### ISSUE TITLE
Nesting exceptions

### ISSUE THREAD

**Issue by teodragovic** [HugoGiraudel/sass-guidelines#70]
While I agree that we should generally avoid nesting there are few instances where it should be allowed:

1. If using component state classses (ie. https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md#componentnameis-stateofcomponent) that don't provide meaning by themselves and can be repeated (imagine having three `.is-active` classes and each triggers different properties)

2. When it can reflect DOM structure that will always be the same like lists (in this case I would limit this just to list items and avoid nested lists) and tables.

3. Scoping components with parent class - ie. using default WordPress classes to add specific styles to homepage etc. or maybe styling particular instance of some javascript plugin that outputs custom markup with classes.

In any case it shouldn't be definetly limited to just one use case as long as we are aware of output.

**Comment by HugoGiraudel** [comment]
I like this. I'll probably use it to complete the nesting section.
