### ISSUE TITLE
Potential zero-value unit issue in guidelines

### ISSUE THREAD

**Issue by davidkpiano** [HugoGiraudel/sass-guidelines#74]
In the Sass guidelines, [it states that](http://sass-guidelin.es/#units):

> When dealing with lengths, a 0 value should never ever have a unit.

First of all, I 1000% agree with this. However, developers may run into calculation issues by following this rule due to a [Sass unitless zero-value calculation issue](https://github.com/sass/sass/issues/1572), and I'm not sure whether it will get resolved or not. To get around the issue, developers will have to specify a unit for zero-values when that value is involved in multiplication/division with another similar unit value:

```sass
// Main Stylesheet
$shelf-width: 100px !default;
$book-width: 10px !default;

$books-per-shelf: floor($shelf-width / $book-width);

.shelf > .book:nth-child(#{$books-per-shelf}n) {
  content: "I'm the last book!";
}

// Developer Stylesheet
// (for the developer who can't afford shelves)

// can't do this!
$shelf-width: 0; // 0/px isn't a valid CSS value.

// forced to do this
$shelf-width: 0px; // Unfortunately goes against the guidelines

@import 'path/to/_main-stylesheet';
```

**Comment by HugoGiraudel** [comment]
Hey David. Let's wait for some extra content on the relevant Sass issue.

**Comment by myqianlan** [comment]
follow this issue

**Comment by HugoGiraudel** [comment]
I am closing. This is a rather specific case that should not be handled in the guidelines.
