### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#83]
Ping @varemenos and @kmargaritis.

**Comment by kmargaritis** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `gr` branch;
1. Copy `index.md` to `gr/index.md`;
1. Translate it. :)

**Comment by kmargaritis** [comment]
Seems great!

**Comment by HugoGiraudel** [comment]
Hey there. Shall I close this? :D

**Comment by varemenos** [comment]
Hey @HugoGiraudel, @margaritis and I returned from vacations recently. We talked right before leaving for vacations and decided to "abuse" a weekend or two to finally finish this.

Really sorry for the huge and inexcusable delay.

**Comment by HugoGiraudel** [comment]
There is no problem. It's open-source contribution; there is no rush at all. Do it when you can/want, and don't stress yourself about it. I just wanted to know if you still plan on working on it. :)

**Comment by margaritis** [comment]
Hey @HugoGiraudel! My apologies as well for the delay! Now that we have recharged our batteries we will finish it pretty soon!

**Comment by HugoGiraudel** [comment]
@varemenos I know you are about to leave for 9 months (on the 20th).
@margaritis, do you have everything you need to take over @varemenos’ work?
Shall I look for another Greek translator to assist you?

**Comment by margaritis** [comment]
Hey @HugoGiraudel! Happy new year! Adonis is indeed leaving! From 19th and onwards he will only have access to an scary Nokia :stuck_out_tongue:! @modkaffes & @sebdesign have already joined the team so i think we can proceed steadily!

**Comment by HugoGiraudel** [comment]
Alright, thank you for keeping me updated. Please tell me if I can do anything to assist you in your contribution.

**Comment by margaritis** [comment]
Will do Hugo! Many thanks!

**Comment by HugoGiraudel** [comment]
Also feel free to add extra contributors in this file: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/languages.yml. :)

**Comment by margaritis** [comment]
:smiley:

**Comment by sebdesign** [comment]
Can't wait to see it live! :)

**Comment by varemenos** [comment]
Everything is ready for release,  margaritis will prepare the PR once he gets some free time :)

**Comment by HugoGiraudel** [comment]
Closed with #299.
