### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#84]
Ping @ghost.

**Comment by PatrickKDK** [comment]
Hi . So should I just start translateing index.md? :)

**Comment by HugoGiraudel** [comment]
Well, here is how I would like to work. 

You can:
1. fork the repository on GitHub;
1. open a branch called `da`;
1. copy `index.md` in `/da/index.md`;
1. translate it. :) 

Code should just stay how it is, and comments within code should probably stay in English as well. 

I am available for any question of course! :)

**Comment by PatrickKDK** [comment]
Allrighty, will do. I'll be sure to write if I have any questions. :)

**Comment by HugoGiraudel** [comment]
Thanks Patrick!

**Comment by matiassingers** [comment]
What is the progress on this translation?

Seems that the user @PatrickKDK was deleted :confused: 
Would be great with a link to the repo/branch where the translation is being done.

**Comment by HugoGiraudel** [comment]
Actually @PatrickKDK has been renamed to @ghost. 

@ghost, what is the current status? :)

**Comment by HugoGiraudel** [comment]
Oh. Ghost is a GitHub reserved account...

**Comment by matiassingers** [comment]
@HugoGiraudel yeah I thought @ghost was just what GitHub redirects to when a user is deleted

**Comment by HugoGiraudel** [comment]
Author disappeared, translation canceled.
