### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#85]
Ping @pierrechoffe.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `fr` branch;
1. Copy `index.md` to `fr/index.md`;
1. Translate it. :)

**Comment by HugoGiraudel** [comment]
> Salut Hugo,
>
>(1) Liens
> Ok pour le lien vers les articles originaux en anglais (dommage, y’a de bonnes trad en français !! :))
Quid des liens vers wikipedia: idem, ou (lorsque c’est possible) lien vers wiki français?
>
> (2) Traduction de Note
> Vu que c’est le même mot (et si je comprends bien c’est la seule chose à traduire), ya rien de particulier à faire pour la trad fr ?
> 
> (3) Questions
> Il y a des points sur lesquels j’ai des questions, donc je te propose d’en faire la liste une fois que j’aurai terminé, avant de te soumettre la trad, ok ?

> @+, Pierre

**Comment by HugoGiraudel** [comment]
@pierrechoffe

1. Yep.
2. Yep.
3. Yep.

**Comment by pierrechoffe** [comment]
Re-salut Hugo,

Bien noté tout cela. J’imagine que le 2e Yep signifie « garder les liens vers wikipedia anglais » .

à part ça, et avant d’aller plus loin, tu te rappelles que je ne suis pas le roi de git (même si je fais les manips de base régulièrement, mais il y a plein de choses que je n’ai jamais faites et jamais apprises).

En suivant le mode d’emploi que tu nous as envoyé, j’arrive à ceci :



Comme tu le vois, je suis sur une branche dans laquelle manquent pas mal d’améliorations apportées depuis 2 jours. Je te donne les manips effectuées (le premier abort étant peut-être la source de tout les pbs) :

iMac-Pierre-Choffe-9:~ pierrechoffe$ cd sass-guidelines
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout gh-pages
error: The following untracked working tree files would be overwritten by checkout:
	index.md
Please move or remove them before you can switch branches.
Aborting
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout -b fr
Switched to a new branch 'fr'
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ cp index.md fr/index.md
cp: fr/index.md: No such file or directory
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git remote add upstream https://github.com/HugoGiraudel/sass-guidelines.git
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git fetch upstream
remote: Counting objects: 120, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 120 (delta 47), reused 73 (delta 27)
Receiving objects: 100% (120/120), 52.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.
From https://github.com/HugoGiraudel/sass-guidelines
 * [new branch]      gh-pages   -> upstream/gh-pages
 * [new branch]      master     -> upstream/master
 * [new branch]      single-quotes -> upstream/single-quotes
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout gh-pages
error: pathspec 'gh-pages' did not match any file(s) known to git.
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git remote -v
origin	https://pierrechoffe@github.com/pierrechoffe/sass-guidelines.git (fetch)
origin	https://pierrechoffe@github.com/pierrechoffe/sass-guidelines.git (push)
upstream	https://github.com/HugoGiraudel/sass-guidelines.git (fetch)
upstream	https://github.com/HugoGiraudel/sass-guidelines.git (push)
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout gh-pages
error: pathspec 'gh-pages' did not match any file(s) known to git.
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout master
A	index.md
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git merge upstream/master
Updating 519dd5a..42c66aa
Fast-forward
 README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout gh-pages
error: pathspec 'gh-pages' did not match any file(s) known to git.
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git checkout fr
A	index.md
Switched to branch 'fr'
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git stash
Saved working directory and index state WIP on fr: 519dd5a Update README.md
HEAD is now at 519dd5a Update README.md
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git fetch
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase origin/gh-pages
First, rewinding head to replay your work on top of it...
Applying: Typos in postprocessors section
Using index info to reconstruct a base tree...
M	index.md
Falling back to patching base and 3-way merge...
Auto-merging index.md
CONFLICT (content): Merge conflict in index.md
Failed to merge in the changes.
Patch failed at 0001 Typos in postprocessors section
The copy of the patch that failed is found in:
   /Users/pierrechoffe/sass-guidelines/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase --continue
Applying: Typos in postprocessors section
Applying: Delete index.md
Using index info to reconstruct a base tree...
M	index.md
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): index.md deleted in Delete index.md and modified in HEAD. Version HEAD of index.md left in tree.
Failed to merge in the changes.
Patch failed at 0002 Delete index.md
The copy of the patch that failed is found in:
   /Users/pierrechoffe/sass-guidelines/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase --abort
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase origin/gh-pages
First, rewinding head to replay your work on top of it...
Applying: Typos in postprocessors section
Using index info to reconstruct a base tree...
M	index.md
Falling back to patching base and 3-way merge...
Auto-merging index.md
CONFLICT (content): Merge conflict in index.md
Failed to merge in the changes.
Patch failed at 0001 Typos in postprocessors section
The copy of the patch that failed is found in:
   /Users/pierrechoffe/sass-guidelines/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase --continue
Applying: Typos in postprocessors section
Applying: Delete index.md
Using index info to reconstruct a base tree...
M	index.md
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): index.md deleted in Delete index.md and modified in HEAD. Version HEAD of index.md left in tree.
Failed to merge in the changes.
Patch failed at 0002 Delete index.md
The copy of the patch that failed is found in:
   /Users/pierrechoffe/sass-guidelines/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git rebase --continue
Applying: Delete index.md
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ git stash pop
Auto-merging index.md
CONFLICT (add/add): Merge conflict in index.md
iMac-Pierre-Choffe-9:sass-guidelines pierrechoffe$ 

* Impossible de faire git checkout gh/pages (à cause du premier aborting?)
* merge conflicts résolus avec l’outil Tower (c’est pour ça que ça n’apparaît pas ici) en prenant la version la plus récente à chaque fois

Mes questions : 
au vu de ce que tu peux constater sur ces deux vues, est-ce que je travaille sur la dernière version? (je pense que non).
comment récupérer la bonne version?
comment avoir toujours une version à jour et retrouver les ajouts récents sans avoir à chercher partout? (je vois que Tower fait des fetch régulièrement mais sans doute pas sur la bonne version…)

Désolé, la traduction est plus mon fort que la gestion de versions…

Merci pour tes éclaircissements,
@+, Pierre
