### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#86]
Ping @ttomdewit.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `nl` branch from `gh-pages` branch;
1. Copy `index.md` to `nl/index.md`;
1. Translate it. :)

**Comment by bartveneman** [comment]
Perhaps I could pick up of review some parts, if needed

**Comment by bartveneman** [comment]
@HugoGiraudel I have my concerns for the Dutch translation. Dutch people tend to have a reasonable knowledge of the English language, so I'm not sure if a translation will be a useful addition. We're quite used to have stuff available in English only. I guess you'd still like this project to be translated, but I'd just like to point this out. Perhaps @ttomdewitt could shine his light in this too.

**Comment by HugoGiraudel** [comment]
I don't specifically want any translation, I just think it is nice for such a document to be available in as many languages as possible. Now, if you think it won't have a point to translate it in Dutch, fair enough. ;)

**Comment by ttomdewit** [comment]
I haven't had time to get on with it. Super busy making some arrangements (more on that soon) and I've had an important couple of weeks at Uni.




Still planning on translating, although Bart is quite right. Still, I sometimes wish such documents were available in my native language because that makes understanding it that much easier.



Kind regards


Tom de Wit

Software Engineer

ttomdewit@gmail.com

@ttomdewit

**Comment by TimonVS** [comment]
I'd be happy to contribute. But at the same time I must agree with @bartveneman, a lot of Dutch people already speak English (around 90%).

**Comment by HugoGiraudel** [comment]
I'd be glad to have a Dutch version nevertheless. :)

**Comment by HugoGiraudel** [comment]
Ohai. Any progress on this or shall I close it? :)

**Comment by bartveneman** [comment]
Not from my side, sorry.

**Comment by HugoGiraudel** [comment]
Hey there! It's been almost 6 months and I don’t really know what is going here. Do you folks work on this at all? Shall I look for extra Dutch translators to assist you / start over? Keep me in touch, thank you. :)

**Comment by TimonVS** [comment]
It'd be a bit pointless if there's no demand for it. So the question is, is there any demand for a Dutch translation?

**Comment by HugoGiraudel** [comment]
Alright. :)

**Comment by bartveneman** [comment]
I think it's a nobel idea to translate it to Dutch, but I agree it's too much work if demand is low or zero.
