### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#87]
Ping @klapec.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `pl` branch from `gh-pages` branch;
1. Copy `index.md` to `pl/index.md`;
1. Translate it. :)

**Comment by klapec** [comment]
I'm having trouble understanding the meaning of these:
```
// Since Sass indented-syntax forces those coding standards
// There is no wrong way of proceeding
```
in http://sass-guidelin.es/#syntax--formatting (Sass syntax selected).

What exactly do you mean by *"those coding standards"*? Does Sass syntax require you to specifically use 2 spaces indents, 80 characters per line, as per the rules above the code block? (*"Roughly we want..."*)

**Comment by HugoGiraudel** [comment]
> What exactly do you mean by "those coding standards"?

I am mostly referring to braces. :)

**Comment by klapec** [comment]
Okay, thanks.

**Comment by klapec** [comment]
*"Note"* element (`.note > p`) has a `::before` on its `:first-child` with `content: "Note – "`. Is it going to stay as a CSS rule? Am I supposed to touch it?

**Comment by HugoGiraudel** [comment]
Actually this will be done in CSS. We'll do something like:

```scss
:lang(pl) .note > ::first-child::before {
  content: "<equivalent_of_note_in_polish> – ";
}
```

**Comment by klapec** [comment]
Hugo, should I indicate in any way that an external link (from `Further reading` sections, for example) is written in a different language? I noticed that you once did this:
```
* [FR] [Sass, une architecture composée](http://slides.com/hugogiraudel/sass-une-architecture-composee)
```
Should I then prepend [EN] to any link that's in English, as well? I've already converted all of the links pointing to Wikipedia articles to their Polish translations.

Also: what about `donate.html`?

**Comment by HugoGiraudel** [comment]
I must say I am not sure. I think we could **not** translate article titles, so that it's bright clear that they are in English, French or whatever and get rid of `[FR]`. What do you think?

I am currently thinking of something for `donate.html`. Don't deal with it now, we'll tackle it later.

**Comment by klapec** [comment]
Yeah, I personally think that link titles are good enough indication of what language they are written in. Language-specific prefixes, like [EN] or [FR] are not really necessary.

I think I'll manage to finish it by tonight. Has anyone else who speaks Polish contacted you? I'm hoping for someone to review my translation before publishing it. I'm obviously trying my best to avoid any spelling errors but I can never be too sure about it :)

**Comment by HugoGiraudel** [comment]
> Yeah, I personally think that link titles are good enough indication of what language they are written in. Language-specific prefixes, like [EN] or [FR] are not really necessary.

Alright. Leave the titles alone, it will be fine this way.

> I think I'll manage to finish it by tonight. Has anyone else who speaks Polish contacted you? I'm hoping for someone to review my translation before publishing it. I'm obviously trying my best to avoid any spelling errors but I can never be too sure about it :)

We will find someone on Twitter, I am not worrying too much about this. Just hit me up when you're done. :)

**Comment by HugoGiraudel** [comment]
Regarding `donate.html`: https://github.com/HugoGiraudel/sass-guidelines/issues/96#issuecomment-70406440.

**Comment by klapec** [comment]
Polish for *Note* is *Uwaga*.

**Comment by HugoGiraudel** [comment]
PR opened: #102.

**Comment by HugoGiraudel** [comment]
Released: https://github.com/HugoGiraudel/sass-guidelines/commit/e961c1c25d4742b31cc5d7aa45a8b184a2aafc00.

**Comment by HugoGiraudel** [comment]
@klapec Hey Andrzej, there has been a slight change in content. Would you care submitting a PR: https://github.com/HugoGiraudel/sass-guidelines/issues/96#issuecomment-70620213? :)

**Comment by klapec** [comment]
Sure, give me few minutes.

**Comment by HugoGiraudel** [comment]
No rush whatsoever.

**Comment by HugoGiraudel** [comment]
Ping @klapec. 

Do you feel like you could translate version 1.1.0? There are not many additions but that would be nice for your translation to remain up-to-date. You can see the changes here: https://github.com/HugoGiraudel/sass-guidelines/pull/125.

Tell me what you think. :)

**Comment by klapec** [comment]
Yup, sorry I've been extra busy lately. I'll update the translation today.
