### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#88]
Ping @kaibrueckers.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `de` branch from `gh-pages` branch;
1. Copy `index.md` to `de/index.md`;
1. Translate it. :)

**Comment by kaibrueckers** [comment]
Sounds good to me ;)
I think I'll already start this weekend, if you have any other tips for me, just let me know.

**Comment by HugoGiraudel** [comment]
Same, if you have an question, be sure to ask. :)

**Comment by altembo** [comment]
ping me if you need help @kaibrueckers

**Comment by altembo** [comment]
@kaibrueckers I think we should do the work on *one* fork/branch and cleary separate our work, to not collide, shouldn't we? So we could review each others commits. As you already forked this project, I would suggest contributing to your fork.

**Comment by kaibrueckers** [comment]
@altembo Sounds like a plan, I had to delete my fork because of some misconfigurations on my side. Bear with me, I'm quite new to this "collaboration-style" type of working with git. Would be great if you can give me some advice on how we should proceed now.

**Comment by altembo** [comment]
@kaibrueckers Me, too ;-) So then let me do the fork, I added you as a Collaborator to my fork. Until we separate our work to not work on the same thing the same time, there should not be any merge problems for us. I will no setup the branch and ping you agian

**Comment by altembo** [comment]
@kaibrueckers checkout my fork of this project and make sure to switch to the "de" branch. As suggested i copied the file to de/index.md. 
If you don't mind I would start from the **beginning** to **commenting**, so your part will be from **architecture** till the end. Ok?

**Comment by altembo** [comment]
@kaibrueckers I just pushed a test-translation to the 'de' branch. So the next step would be to review it (by u ;-)). If it passed, comment it, if not, comment it, too :P Make sure to push your commit as far as you finished a section. I think one commit per section should be fine.

**Comment by kaibrueckers** [comment]
Great, thanks. Alright, I already translated some of the introductory stuff, so I'll go through your version and make some suggestions if necessary. I'll start working on it again tonight :)

**Comment by altembo** [comment]
Oh damn, I knew it would have been better to let you start from the beginning ;-( Lets meet in Gitter for further communication/discussion, you should have got an invitation from HugoGiraudel

**Comment by davidhellmann** [comment]
Los @kaibrueckers gib gas, ich will deutsch lesen :P

**Comment by kaibrueckers** [comment]
Wir sind dran, es zieht sich gerade etwas ;)

**Comment by altembo** [comment]
@davidhellmann hilfe ist immer gern gesehen ;-)

**Comment by davidhellmann** [comment]
Glaub ich. Aber im Moment fehlt mir glaube gerade auch die Zeit. Aber was müsste ich denn tun wenn ich helfen soll?

**Comment by altembo** [comment]
@davidhellmann Ja uns (zumindest mir :>) im Moment leider auch. Sofern Du Zeit hast schnapp Dir ein unübersetztes Kapitel (= kein Branch vorhanden) in meinem Fork, erstell nen Branch und push Ihn damit wir sehen das Du dran arbeitest. Und wenn Du fertig übersetzt hast machst nen PullRequest auf.

**Comment by davidhellmann** [comment]
Ich muss mal schauen. Ich verspreche jetzt mal nichts hab es aber mit auf dem Schirm, ok?!

**Comment by morkro** [comment]
Hey guys (@davidhellmann, @kaibrueckers  & @altembo),

how is your progress? It's been almost 3 month now since your last conversation. 
Are you still working on this? If not, I would like to complete the work you've done so far.

Just leave me a message :)

**Comment by davidhellmann** [comment]
I'm move next week from

cologne to salzburg and the last weeks/months were stressful and I've no time for anything. Sorry :/




best from the DB Train












David Hellmann

Art Director & Frontend Developer

50931 cologne

Germany




———




CONTACT

— davidhellmann.com@gmail.com

— http://davidhellmann.com




SOCIAL ACCOUNTS

— http://twitter.com/davidhellmann 

— http://pinterest.com/davidhellmann 

— http://instagram.com/davidhellmann




OTHER SITES

— http://makebetterwebsites.com

— http://makebettershirts.com 

— http://superb.li

**Comment by morkro** [comment]
Alright, gotcha. 
@HugoGiraudel and I agreed on that I will just continue and take over the german translation for now. Unless someone of you says otherwise though. Then we can still merge our progress :)

**Comment by altembo** [comment]
@morkro:
Ye, translation is kind of frozen right now. Everytime I want to continue something else blocks me. 
I added you as a collaborator to my fork, so you can continue/review our work.

**Comment by morkro** [comment]
Thanks @altembo.
I already forked it myself though as I was talking with Hugo :( I guessed you may not answer so quick. 
But still, I took a look into your work and will add some of it. Of course with credits to you guys. 

When you find the time to continue, just leave me a message here :) Then we find a solution how to proceed. Is that okay for you guys?

**Comment by altembo** [comment]
@morkro 
Okay, but then we should freeze the work on my branch completely and continue working on your fork instead (when we return). fyi @kaibrueckers , @davidhellmann

**Comment by morkro** [comment]
Alright. Drop me a line when you return ;)

**Comment by qcon** [comment]
@morkro was ist bisher schon fertig, ich möchte auch ein bisschen mitwirken

**Comment by morkro** [comment]
Hey @qcon,

Ich bin mittlerweile fertig und muss nur noch kleine Korrekturen vornehmen. :)
Montag/Dienstag kommt der Pull-Request!

**Comment by qcon** [comment]
okay, top. Hab' s grad in deinen Fork entdeckt. Super arbeit, Danke!

**Comment by morkro** [comment]
Danke :)
