### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#89]
Ping @magalhini.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `pt` branch;
1. Copy `index.md` to `pt/index.md`;
1. Translate it. :)

**Comment by magalhini** [comment]
Ah just noticed that the documents are all living on a different branch.
I'll be on it :)

Again, good work on this stuff.

**Comment by HugoGiraudel** [comment]
Thanks for your help!

**Comment by eduardoboucas** [comment]
@magalhini Let me know if you need any help. :)

**Comment by SaraVieira** [comment]
@magalhini Same here ! If you need help let me know :)

**Comment by magalhini** [comment]
@eduardoboucas and @SaraVieira thanks for your help! I already got a couple more people interested in translating this as well, so we should be able to make this a quick one.

Later today I'll try and section it for translation for all of us then; any particular section you wish to be translating?

**Comment by HugoGiraudel** [comment]
Now, *that* is some cool translation team work. :)

**Comment by eduardoboucas** [comment]
@magalhini I'm cool with any section, whatever works best for you.

(That's how the Portuguese roll, Hugo!)

**Comment by HugoGiraudel** [comment]
> (That's how the Portuguese roll, Hugo!)

![Awesome](http://img.pandawhale.com/post-3890-Bill-Murray-Youre-awesome-85vL.jpeg)

**Comment by SaraVieira** [comment]
That's great @magalhini ! I am also good with any section you put my way

**Comment by magalhini** [comment]
Hey peeps,

I took an initial stab at splitting the content to be translated. This was completely random and I haven't really checked for the amount of words each one of us got, if anyone feels like doing a more even split feel free to suggest it!

I already started with the initial bit, so I might as well carry on with it.
Please make sure you follow the guide @HugoGiraudel write for collaboration, which can be found here: https://github.com/HugoGiraudel/sass-guidelines/issues/96

@magalhini

* [About The Author](#about-the-author)
* [Contributing](#contributing)
* [About Sass](#about-sass)
  * [Ruby Sass Or LibSass](#ruby-sass-or-libsass)
  * [Sass Or SCSS](#sass-or-scss)
  * [Other Preprocessors](#other-preprocessors)
* [Introduction](#introduction)
  * [Why A Styleguide](#why-a-styleguide)
  * [Disclaimer](#disclaimer)
  * [Key Principles](#key-principles)
* [Syntax & Formatting](#syntax--formatting)
  * [Strings](#strings)
  * [Numbers](#numbers)
    * [Zeros](#zeros)
    * [Units](#units)
    * [Calculations](#calculations)
    * [Magic numbers](#magic-numbers)
  * [Colors](#colors)
    * [Color formats](#color-formats)
    * [Colors and variables](#colors-and-variables)
    * [Lightening and Darkening Colors](#lightening-and-darkening-colors)

@eduardoboucas 
  * [Lists](#lists)
  * [Maps](#maps)
    * [Debugging A Sass Map](#debugging-a-sass-map)
  * [CSS Ruleset](#css-ruleset)
  * [Declaration Sorting](#declaration-sorting)
  * [Selector Nesting](#selector-nesting)
    * [General Rule](#general-rule)
    * [Exceptions](#exceptions)
* [Naming Conventions](#naming-conventions)
  * [Constants](#constants)
  * [Namespace](#namespace)
* [Commenting](#commenting)
  * [Writing Comments](#writing-comments)
  * [Documentation](#documentation)

@SaraVieira 
* [Architecture](#architecture)
  * [Components](#components)
  * [The 7-1 pattern](#the-7-1-pattern)
    * [Base Folder](#base-folder)
    * [Components Folder](#components-folder)
    * [Layout Folder](#layout-folder)
    * [Pages Folder](#pages-folder)
    * [Themes Folder](#themes-folder)
    * [Utils Folder](#utils-folder)
    * [Vendors Folder](#vendors-folder)
    * [Main file](#main-file)
  * [Shame file](#shame-file)

@couto
* [Responsive Web Design and Breakpoints](#responsive-web-design-and-breakpoints)
  * [Naming Breakpoints](#naming-breakpoints)
  * [Breakpoint manager](#breakpoint-manager)
  * [Media Queries Usage](#media-queries-usage)
* [Variables](#variables)
  * [Scoping](#scoping)
  * [!default Flag](#default-flag)
  * [!global Flag](#global-flag)
  * [Multiple Variables Or Map](#multiple-variables-or-maps)
* [Extend](#extend)
* [Mixins](#mixins)
  * [Basics](#basics)
  * [Arguments list](#arguments-list)
  * [Mixins and Vendor Prefixes](#mixins-and-vendor-prefixes)
* [Conditional statements](#conditional-statements)

@gnclmorais
* [Loops](#loops)
  * [Each](#each)
  * [For](#for)
  * [While](#while)
* [Warnings and errors](#warnings-and-errors)
  * [Warnings](#warnings)
  * [Errors](#errors)
* [Tools](#tools)
  * [Compass](#compass)
  * [Grid Systems](#grid-systems)
  * [SCSS-lint](#scss-lint)
* [Too Long; Didn't Read](#too-long-didnt-read)

Tell me your thoughts!

**Comment by HugoGiraudel** [comment]
If you need anything guys, be sure to ask.

**Comment by Couto** [comment]
Got it! I'm quite busy for today (and quite probably the next couple days) but I'll be all over those words as soon as possible! :cake:

**Comment by eduardoboucas** [comment]
I don't want to be a party pooper, but are we sure it's a good idea to have 5 people translating this? I reckon it'll be quite hard to maintain a consistent writing style across the document (i.e. attempting a translation of technical terms VS. using the English word, applying the new spelling agreement, etc.).

**Comment by HugoGiraudel** [comment]
As long as there are full-length proofreadings afterwards, I think it should be okay. Although, you decide of course.

**Comment by gnclmorais** [comment]
I’m with @HugoGiraudel. I don’t mind each person translating his/her part on its own, as long as then we cross-reference out bits & proofread the whole thing. Also, if necessary, we can use something like [Gitter](https://gitter.im) to talk about this project in real time, if there’s an issue to discuss.

**Comment by SaraVieira** [comment]
@magalhini, @eduardoboucas , @Couto , @gnclmorais How do you guys wanna proceed regarding the spelling reform ? Use the old or new ?

I should get started this week :)

**Comment by Couto** [comment]
@SaraVieira as much as I love the old spelling agreement, I guess we all need to let it go and start using the new one, but it's just my opinion.

**Comment by gnclmorais** [comment]
Agree with @Couto. I don’t like it, but feels to be the right approach.

**Comment by HugoGiraudel** [comment]
> Also, if necessary, we can use something like Gitter to talk about this project in real time, if there’s an issue to discuss.

I opened a Gitter room for Sass Guidelines yersterday. You should have all been invited. Feel free to discuss (in English in the general channel).

**Comment by magalhini** [comment]
@saravieira, @gnclmorais and @eduardoboucas, since we need to merge it all together in one repo before submitting the pull request back to @HugoGiraudel 's repo, where should we merge our changes? 
Feel free to merge your changes into my repo if you'd like, I'll take care of sorting them out.

**Comment by gnclmorais** [comment]
@magalhini, I think we should merge everything on your repository, then.

**Comment by magalhini** [comment]
@SaraVieira @eduardoboucas @Couto I only got @gnclmorais' pull request so far. What's the status on your translations then? Let's get this done, we've shamefully made @HugoGiraudel wait long enough :)

**Comment by Couto** [comment]
Sorry, I had some really rough weeks, and this is my first free day. (yay!)

I should have everything ready (at least waiting for you revision) by tonight.

**Comment by magalhini** [comment]
I'm still waiting for those pull requests, @SaraVieira @eduardoboucas and @Couto :) What's the status? So far only @gnclmorais 's translation has been merged into my branch.

**Comment by magalhini** [comment]
@gnclmorais Merged manually the translations from the other guys, I've updated the original repo with his changes. There are still some changes left to be translated, me and Gonçalo will see what happened there.

But these should (finally!) be done very very very soon!

**Comment by magalhini** [comment]
@HugoGiraudel We believe this is all done now! What happens next? :)

**Comment by HugoGiraudel** [comment]
I review, patch, merge and we celebrate. :)
