### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#90]
Ping @soniar4i.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `es` branch from `gh-pages` branch;
1. Copy `index.md` to `es/index.md`;
1. Translate it. :)

**Comment by soniar4i** [comment]
Great! I'm on it :)

Please, let me know if you need something else or if it's anything I'm doing wrong :)

**Comment by HugoGiraudel** [comment]
Ping @davidkpiano who wanted to contribute as well. Better two than one. ;)

**Comment by fernandomartinez** [comment]
Hi guys if you need any help translating or spell checking, please count me in :)

**Comment by soniar4i** [comment]
Hey @fernandomartinez It would be great if you read what I translated, in case there's any mistake. I'm working on it right now! I hope tonight I'll commit more changes. :)

**Comment by HugoGiraudel** [comment]
From @fernandomartinez:

> Here's one paragraph, please confirm if this is ok and useful, so I can continue checking the guide. Also please feel free to ignore anything you consider irrelevant.

> On the first paragraph after the contribute title:
> "Esta guía de Sass es un proyecto libre que mantengo en mi tiempo libre. Sobra decir que que es una cantidad enorme de trabajo para mantenerlo todo actualizado, documentado y relevante. Obviamente, apreciaré muchísimo saber que te ha gustado esta guía de estilo."

> This could be:
> "Sass Guidelines es un proyecto abierto que mantengo en mi tiempo libre. Sobra decir que lleva una cantidad enorme de trabajo mantenerlo vigente, documentado y relevante. Obviamente, apreciaré muchísimo saber que te ha gustado esta guía de estilo."

**Comment by soniar4i** [comment]
Good. The first line sounds better than mine! I'll make the changes :+1:

**Comment by soniar4i** [comment]
Well, I've submitted the spanish translations, please let me know if theres something wrong, I'm worried about the special characters on ToC.
