### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#92]
Ping @pavelantolik.

**Comment by HugoGiraudel** [comment]
Just for the record, here is the ideal way of working (for me, at least):

1. Fork the repository on GitHub;
1. Open a `cz` branch from `gh-pages` branch;
1. Copy `index.md` to `cz/index.md`;
1. Translate it. :)

**Comment by pavelantolik** [comment]
Hi Hugo,

I've got the repository cloned to my laptop, but I'm still kinda new in GitHub (we use Subversion at work, so my relationship with GitHub so far has been "visitor only"). So I could use a little hint - what exactly does it take to "open a cz branch"? Don't wanna mess anything up :))

**Comment by a5e** [comment]
1. `git checkout gh-pages && git checkout -b cz && mkdir cz && cp index.md cz/index.md`
2. translate cz/index.md
3. `git commit -am "added cz translation fixes #92"`
4. `git push origin cz`
5. go to github and click the PR button.

Hope this is clear, feel free to ask if it isn't

**Comment by HugoGiraudel** [comment]
Thanks Antoine for the heads up.

Adding to this, you have to know that when you create a new branch (`git checkout -b <branch_name>`), you are using the state of the current branch. That's why you have to put yourself on the `gh-pages` branch before creating your own, rather than `master` (which is empty).

More information here: https://github.com/HugoGiraudel/sass-guidelines/issues/96.

**Comment by HoBi** [comment]
@HugoGiraudel hi, I will try translate the guidelines to Czech lang, If you want... :) 
I can not see any work done - so pavelantolik probably did not start, right?

**Comment by HugoGiraudel** [comment]
Hello. That's good news. I think it is safe to assume that you will be on
your own on this.

**Comment by HoBi** [comment]
@HugoGiraudel ok, cool. :)

Should I use shortcut for translate according to the Czech republic -> **CZ** (https://countrycode.org/czechrepublic) *or* for czech lang -> **CS** (http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)? :)

**Comment by Grawl** [comment]
I think `cz` will be better.

**Comment by HugoGiraudel** [comment]
cz sounds good to me.

**Comment by HoBi** [comment]
Here is my progress. *Translation is probably not excellent, but I am going to improve it.* :smiley_cat: 

- [x] About the author
- [ ] Contributing
- [x] Table of Contents
- [ ] About Sass
- [ ] Introduction
- [ ] Syntax & formatting
- [ ] Naming conventions
- [x] Commenting
- [x] Architecture
- [ ] Responsive Web Design and breakpoints
- [ ] Variables
- [ ] Extend
- [ ] Mixins
- [ ] Conditional statements
- [ ] Loops
- [ ] Warnings and Errors
- [ ] Tools
- [ ] Too Long; Didn’t read

**Comment by HugoGiraudel** [comment]
I am really looking forward to it! :)

**Comment by HoBi** [comment]
Only 5, small, sections left. :)

Can I release (after that) something like 1.1.0-beta, which will may not have translated codes from _include/ and will may not have stunningly perfect translation?

... just to have it avaible as beta for impatient people? :smile_cat:

**Comment by HugoGiraudel** [comment]
We cannot release a beta, and I am not willing to do so. However, I am perfectly fine to release the Czech version with English code snippets. We can translate them later on. :)

**Comment by HoBi** [comment]
OK, no problem. :+1:

**Comment by HugoGiraudel** [comment]
Great. :)

**Comment by HoBi** [comment]
I am really like that I can translate this awesome guidelines, because I can learn a lot from both English and Sass. :smirk_cat: 

Well, I think I am done. :+1: 
// I have cheked all once again and I think and I hope it is OK. :smirk_cat:

**Comment by HugoGiraudel** [comment]
Alright. Let me review it right now.

**Comment by HoBi** [comment]
@HugoGiraudel is any chance to make my own IDs for headings? Czech have some extra characters English do not and it only make some babble, which is not so much semantic. :smirk_cat:

**Comment by HugoGiraudel** [comment]
Nope. Not possible. Sorry.

**Comment by HoBi** [comment]
So there are some task I want to make for next merge:

* [ ] fix potential typo errors
* [ ] fix links referring to headings
* [ ] translate code snippets

**Comment by HugoGiraudel** [comment]
Sounds good. :)

**Comment by HoBi** [comment]
I'm sorry, but I had been on sumer camp and the rest of the time I have worked on a project. Now I am going to surgery, but I will try to finish this ASAP after I will be +- OK. :smile_cat:

**Comment by HugoGiraudel** [comment]
I hope everything is fine. Take care!

**Comment by HoBi** [comment]
I will continue with translations. 👍

**Comment by HoBi** [comment]
Btw. @HugoGiraudel should I after translation will be done open PR to your master or gh-pages? Kind of do not know the difference in Jekyll. But other open PR to master so I should do the same?

**Comment by HoBi** [comment]
E.g. I am not sure if 

1.
```bash
git checkout gh-pages
git checkout -b cz
```

2.
```bash
git checkout master
git checkout -b cz
```

**Comment by HugoGiraudel** [comment]
`master`, we don’t use `gh-pages` anymore. It’s obsolete. :)

**Comment by HugoGiraudel** [comment]
@HoBi Do you need this issue to be open or can I close it?

**Comment by HoBi** [comment]
@HugoGiraudel you can close it. I continue on traslation and updates on my forked repo and then i will do a pull request. :-)
