### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#97]
Ping @grawl.

**Comment by HugoGiraudel** [comment]
PR opened: #99.

**Comment by HugoGiraudel** [comment]
Please, could you submit a PR to update this line: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L120?

Adding something like ", translated by ..." in Russian, with Markdown links would be nice. Kind of what has been done for the Polish translation: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L100.

**Comment by Grawl** [comment]
Oh I thinked about this string yesterday. I want to translate your name into russian transliteration. And yes, it will be nice to add translators here.

**Comment by Grawl** [comment]
#176

**Comment by HugoGiraudel** [comment]
Ping @Grawl. 

Do you feel like you could translate version 1.1.0? There are not many additions but that would be nice for your translation to remain up-to-date. You can see the changes here: https://github.com/HugoGiraudel/sass-guidelines/pull/125.

Tell me what you think. :)
